import "./base.d.ts";
import "./drawings-layer.d.ts";
import "./lighting-layer.d.ts";
import "./notes-layer.d.ts";
import "./sounds-layer.d.ts";
import "./template-layer.d.ts";
import "./tiles-layer.d.ts";
import "./token-layer.d.ts";
import "./walls-layer.d.ts";
