const ARMOR_CATEGORIES = ["unarmored", "light", "medium", "heavy"] as const;

const ARMOR_PROPERTY_RUNE_TYPES = new Set([
    "advancing",
    "aimAiding",
    "acidEnergyResistant",
    "antimagic",
    "assisting",
    "bitter",
    "coldEnergyResistant",
    "deathless",
    "electricityEnergyResistant",
    "energyAbsorbing",
    "energyAdaptive",
    "ethereal",
    "fireEnergyResistant",
    "fortification",
    "glamered",
    "greaterAcidResistant",
    "greaterAdvancing",
    "greaterColdResistant",
    "greaterDread",
    "greaterElectricityResistant",
    "greaterEnergyAbsorbing",
    "greaterFireResistant",
    "greaterFortification",
    "greaterInvisibility",
    "greaterQuenching",
    "greaterReady",
    "greaterShadow",
    "greaterSwallowSpike",
    "greaterSlick",
    "greaterStanching",
    "greaterWinged",
    "gliding",
    "immovable",
    "implacable",
    "invisibility",
    "lesserDread",
    "magnetizing",
    "majorQuenching",
    "majorSlick",
    "majorShadow",
    "majorSwallowSpike",
    "majorStanching",
    "misleading",
    "moderateDread",
    "portable",
    "quenching",
    "ready",
    "rockBraced",
    "shadow",
    "sinisterKnight",
    "slick",
    "soaring",
    "spellbreaking",
    "stanching",
    "swallowSpike",
    "trueStanching",
    "trueQuenching",
    "winged",
] as const);

export { ARMOR_CATEGORIES, ARMOR_PROPERTY_RUNE_TYPES };
