import { SenseAcuity, SenseType } from "./index.ts";

const ALLIANCES = new Set(["party", "opposition", null] as const);

const SAVING_THROW_DEFAULT_ATTRIBUTES = {
    fortitude: "con",
    reflex: "dex",
    will: "wis",
} as const;

/** Use the lower end of CRB Table 9-1 ("Size and Reach"), allowing individual attacks to specify otherwise */
const SIZE_TO_REACH = {
    tiny: 0,
    sm: 5,
    med: 5,
    lg: 5,
    huge: 10,
    grg: 15,
} as const;

const SENSE_TYPES = new Set([
    "darkvision",
    "echolocation",
    "greater-darkvision",
    "infrared-vision",
    "lifesense",
    "low-light-vision",
    "motion-sense",
    "scent",
    "see-invisibility",
    "spiritsense",
    "thoughtsense",
    "tremorsense",
    "truesight",
    "wavesense",
] as const);

/** Sense types associated with a particular acuities by definition */
const SENSES_WITH_MANDATORY_ACUITIES: { [K in SenseType]?: SenseAcuity } = {
    darkvision: "precise",
    echolocation: "precise",
    "greater-darkvision": "precise",
    "infrared-vision": "precise",
    "low-light-vision": "precise",
    "motion-sense": "precise",
    "see-invisibility": "precise",
    truesight: "precise",
};

const SENSES_WITH_UNLIMITED_RANGE = [
    "darkvision",
    "greater-darkvision",
    "low-light-vision",
    "see-invisibility",
] as const;

const SENSE_ACUITIES = ["precise", "imprecise", "vague"] as const;

const LANGUAGES = [
    "adlet",
    "akitonian",
    "aklo",
    "alghollthu",
    "amurrun",
    "anadi",
    "ancient-osiriani",
    "androffan",
    "anugobu",
    "arboreal",
    "arcadian",
    "azlanti",
    "boggard",
    "calda",
    "caligni",
    "chthonian",
    "common",
    "cyclops",
    "daemonic",
    "destrachan",
    "diabolic",
    "draconic",
    "drooni",
    "dwarven",
    "dziriak",
    "ekujae",
    "elder-thing",
    "elven",
    "empyrean",
    "erutaki",
    "fey",
    "formian",
    "garundi",
    "girtablilu",
    "gnomish",
    "goblin",
    "goloma",
    "grioth",
    "grippli",
    "halfling",
    "hallit",
    "hwan",
    "iblydan",
    "ikeshti",
    "immolis",
    "iruxi",
    "jistkan",
    "jotun",
    "jyoti",
    "kaava",
    "kashrishi",
    "kelish",
    "kholo",
    "kibwani",
    "kitsune",
    "kovintal",
    "lirgeni",
    "mahwek",
    "migo",
    "minaten",
    "minkaian",
    "muan",
    "munavri",
    "mwangi",
    "mzunu",
    "nagaji",
    "necril",
    "ocotan",
    "okaiyan",
    "orcish",
    "orvian",
    "osiriani",
    "petran",
    "protean",
    "pyric",
    "rasu",
    "ratajin",
    "razatlani",
    "requian",
    "russian",
    "sakvroth",
    "samsaran",
    "sasquatch",
    "senzar",
    "shadowtongue",
    "shae",
    "shisk",
    "shoanti",
    "shobhad",
    "shoony",
    "shory",
    "skald",
    "sphinx",
    "strix",
    "sussuran",
    "taldane",
    "talican",
    "tekritanin",
    "tengu",
    "thalassic",
    "thassilonian",
    "tien",
    "utopian",
    "vanara",
    "varisian",
    "varki",
    "vishkanyan",
    "vudrani",
    "wildsong",
    "wyrwood",
    "xanmba",
    "yithian",
    "ysoki",
] as const;

export {
    ALLIANCES,
    LANGUAGES,
    SAVING_THROW_DEFAULT_ATTRIBUTES,
    SENSES_WITH_MANDATORY_ACUITIES,
    SENSES_WITH_UNLIMITED_RANGE,
    SENSE_ACUITIES,
    SENSE_TYPES,
    SIZE_TO_REACH,
};
