import { CharacterPF2e, FamiliarPF2e, HazardPF2e, LootPF2e, NPCPF2e, VehiclePF2e } from "@actor";
import { SenseAcuity, SenseType } from "@actor/creature/sense";
import { Alignment } from "@actor/creature/types";
import { ActorType } from "@actor/data";
import {
    ActionItemPF2e,
    AncestryPF2e,
    ArmorPF2e,
    BackgroundPF2e,
    BookPF2e,
    ClassPF2e,
    ConditionPF2e,
    ConsumablePF2e,
    ContainerPF2e,
    DeityPF2e,
    EffectPF2e,
    EquipmentPF2e,
    FeatPF2e,
    HeritagePF2e,
    KitPF2e,
    LorePF2e,
    MeleePF2e,
    SpellcastingEntryPF2e,
    SpellPF2e,
    TreasurePF2e,
    WeaponPF2e,
} from "@item";
import { AfflictionPF2e } from "@item/affliction/document";
import { ConditionSlug } from "@item/condition/data";
import { RANGE_TRAITS } from "@item/data/values";
import { DeityDomain } from "@item/deity/types";
import { FeatType } from "@item/feat/data";
import { WEAPON_PROPERTY_RUNES } from "@item/physical/runes";
import { PreciousMaterialGrade } from "@item/physical/types";
import {
    BaseWeaponType,
    MeleeWeaponGroup,
    WeaponGroup,
    WeaponPropertyRuneType,
    WeaponReloadTime,
} from "@item/weapon/types";
import { Size } from "@module/data";
import { JournalSheetPF2e } from "@module/journal-entry/sheet";
import { DAMAGE_TYPES } from "@system/damage";
import { DamageCategoryUnique, DamageType } from "@system/damage/types";
import { pick, sluggify } from "@util";
import enJSON from "../../../static/lang/en.json";
import { immunityTypes, resistanceTypes, weaknessTypes } from "./iwr";
import {
    actionTraits,
    alignmentTraits,
    ancestryItemTraits,
    ancestryTraits,
    armorTraits,
    classTraits,
    consumableTraits,
    creatureTraits,
    damageTraits,
    energyDamageTypes,
    equipmentTraits,
    featTraits,
    hazardTraits,
    magicSchools,
    magicTraditions,
    npcAttackTraits,
    otherArmorTags,
    otherConsumableTags,
    otherWeaponTags,
    preciousMaterials,
    spellOtherTraits,
    spellTraits,
    vehicleTraits,
    weaponTraits,
} from "./traits";

export type StatusEffectIconTheme = "default" | "blackWhite";

const actorTypes: Record<ActorType, string> = {
    character: "ACTOR.TypeCharacter",
    familiar: "ACTOR.TypeFamiliar",
    hazard: "ACTOR.TypeHazard",
    loot: "ACTOR.TypeLoot",
    npc: "ACTOR.TypeNpc",
    vehicle: "ACTOR.TypeVehicle",
};

// Senses
const senses: Record<SenseType, string> = {
    darkvision: "PF2E.Actor.Creature.Sense.Type.Darkvision",
    echolocation: "PF2E.Actor.Creature.Sense.Type.Echolocation",
    greaterDarkvision: "PF2E.Actor.Creature.Sense.Type.GreaterDarkvision",
    lifesense: "PF2E.Actor.Creature.Sense.Type.Lifesense",
    lowLightVision: "PF2E.Actor.Creature.Sense.Type.LowLightVision",
    motionsense: "PF2E.Actor.Creature.Sense.Type.Motionsense",
    scent: "PF2E.Actor.Creature.Sense.Type.Scent",
    seeInvisibility: "PF2E.Actor.Creature.Sense.Type.SeeInvisibility",
    spiritsense: "PF2E.Actor.Creature.Sense.Type.Spiritsense",
    tremorsense: "PF2E.Actor.Creature.Sense.Type.Tremorsense",
    wavesense: "PF2E.Actor.Creature.Sense.Type.Wavesense",
};

// Sense acuity
const senseAcuity: Record<SenseAcuity, string> = {
    imprecise: "PF2E.Actor.Creature.Sense.Acuity.Imprecise",
    precise: "PF2E.Actor.Creature.Sense.Acuity.Precise",
    vague: "PF2E.Actor.Creature.Sense.Acuity.Vague",
};

const weaponPropertyRunes = {
    ...Object.entries(WEAPON_PROPERTY_RUNES).reduce((accumulated, [slug, rune]) => {
        return { ...accumulated, [slug]: rune.name };
    }, {} as Record<WeaponPropertyRuneType, string>),
};

const damageCategoriesUnique: Record<DamageCategoryUnique, string> = {
    persistent: "PF2E.ConditionTypePersistentShort",
    precision: "PF2E.Damage.Precision",
    splash: "PF2E.TraitSplash",
};

const materialDamageEffects = pick(preciousMaterials, [
    "abysium",
    "adamantine",
    "cold-iron",
    "djezet",
    "mithral",
    "noqual",
    "peachwood",
    "silver",
    "sisterstone-dusk",
    "sisterstone-scarlet",
    "sovereign-steel",
    "warpglass",
]);

const damageCategories = {
    ...damageCategoriesUnique,
    ...materialDamageEffects,
    alignment: "PF2E.Alignment",
    energy: "PF2E.TraitEnergy",
    physical: "PF2E.TraitPhysical",
};

const physicalDamageTypes = {
    bleed: "PF2E.TraitBleed",
    bludgeoning: "PF2E.TraitBludgeoning",
    piercing: "PF2E.TraitPiercing",
    slashing: "PF2E.TraitSlashing",
};

const damageTypes: Record<DamageType, string> = {
    ...alignmentTraits,
    ...energyDamageTypes,
    ...physicalDamageTypes,
    mental: "PF2E.TraitMental",
    poison: "PF2E.TraitPoison",
    untyped: "PF2E.TraitUntyped",
};

const damageRollFlavors = [...DAMAGE_TYPES].reduce((result, key) => {
    result[key] = `PF2E.Damage.RollFlavor.${key}`;
    return result;
}, {} as Record<DamageType, string>);

/** Non-detection- and attitude- related conditions added to the Token HUD */
const tokenHUDConditions = {
    blinded: "PF2E.ConditionTypeBlinded",
    broken: "PF2E.ConditionTypeBroken",
    clumsy: "PF2E.ConditionTypeClumsy",
    concealed: "PF2E.ConditionTypeConcealed",
    confused: "PF2E.ConditionTypeConfused",
    controlled: "PF2E.ConditionTypeControlled",
    dazzled: "PF2E.ConditionTypeDazzled",
    deafened: "PF2E.ConditionTypeDeafened",
    doomed: "PF2E.ConditionTypeDoomed",
    drained: "PF2E.ConditionTypeDrained",
    dying: "PF2E.ConditionTypeDying",
    encumbered: "PF2E.ConditionTypeEncumbered",
    enfeebled: "PF2E.ConditionTypeEnfeebled",
    fascinated: "PF2E.ConditionTypeFascinated",
    fatigued: "PF2E.ConditionTypeFatigued",
    "flat-footed": "PF2E.ConditionTypeFlatFooted",
    fleeing: "PF2E.ConditionTypeFleeing",
    frightened: "PF2E.ConditionTypeFrightened",
    grabbed: "PF2E.ConditionTypeGrabbed",
    immobilized: "PF2E.ConditionTypeImmobilized",
    invisible: "PF2E.ConditionTypeInvisible",
    paralyzed: "PF2E.ConditionTypeParalyzed",
    "persistent-damage": "PF2E.ConditionTypePersistent",
    petrified: "PF2E.ConditionTypePetrified",
    prone: "PF2E.ConditionTypeProne",
    quickened: "PF2E.ConditionTypeQuickened",
    restrained: "PF2E.ConditionTypeRestrained",
    sickened: "PF2E.ConditionTypeSickened",
    slowed: "PF2E.ConditionTypeSlowed",
    stunned: "PF2E.ConditionTypeStunned",
    stupefied: "PF2E.ConditionTypeStupefied",
    unconscious: "PF2E.ConditionTypeUnconscious",
    undetected: "PF2E.ConditionTypeUndetected",
    wounded: "PF2E.ConditionTypeWounded",
};

const conditionTypes: Record<ConditionSlug, string> = {
    ...tokenHUDConditions,
    friendly: "PF2E.ConditionTypeFriendly",
    helpful: "PF2E.ConditionTypeHelpful",
    hidden: "PF2E.ConditionTypeHidden",
    hostile: "PF2E.ConditionTypeHostile",
    indifferent: "PF2E.ConditionTypeIndifferent",
    observed: "PF2E.ConditionTypeObserved",
    unfriendly: "PF2E.ConditionTypeUnfriendly",
    unnoticed: "PF2E.ConditionTypeUnnoticed",
};

const weaponCategories = {
    simple: "PF2E.WeaponTypeSimple",
    martial: "PF2E.WeaponTypeMartial",
    advanced: "PF2E.WeaponTypeAdvanced",
    unarmed: "PF2E.WeaponTypeUnarmed",
};

const baseWeaponTypes = Object.keys(enJSON.PF2E.Weapon.Base).reduce(
    (map, slug) => ({
        ...map,
        [slug]: `PF2E.Weapon.Base.${slug}`,
    }),
    {} as Record<BaseWeaponType, string>
);

/** Base weapon types that are considered equivalent for all rules purposes */
const equivalentWeapons = {
    "composite-longbow": "longbow",
    "composite-shortbow": "shortbow",
    "big-boom-gun": "hand-cannon",
    "spoon-gun": "hand-cannon",
} as const;

const rangeDescriptions = RANGE_TRAITS.reduce(
    (descriptions, trait) => mergeObject(descriptions, { [trait]: "PF2E.TraitDescriptionRange" }),
    {} as Record<typeof RANGE_TRAITS[number], string>
);

const preciousMaterialDescriptions = {
    abysium: "PF2E.PreciousMaterialAbysiumDescription",
    adamantine: "PF2E.PreciousMaterialAdamantineDescription",
    "cold-iron": "PF2E.PreciousMaterialColdIronDescription",
    darkwood: "PF2E.PreciousMaterialDarkwoodDescription",
    djezet: "PF2E.PreciousMaterialDjezetDescription",
    dragonhide: "PF2E.PreciousMaterialDragonhideDescription",
    "grisantian-pelt": "PF2E.PreciousMaterialGrisantianPeltDescription",
    inubrix: "PF2E.PreciousMaterialInubrixDescription",
    mithral: "PF2E.PreciousMaterialMithralDescription",
    noqual: "PF2E.PreciousMaterialNoqualDescription",
    orichalcum: "PF2E.PreciousMaterialOrichalcumDescription",
    siccatite: "PF2E.PreciousMaterialSiccatiteDescription",
    silver: "PF2E.PreciousMaterialSilverDescription",
    "sisterstone-dusk": "PF2E.PreciousMaterialSisterstoneDescription",
    "sisterstone-scarlet": "PF2E.PreciousMaterialSisterstoneDescription",
    "sovereign-steel": "PF2E.PreciousMaterialSovereignSteelDescription",
    warpglass: "PF2E.PreciousMaterialWarpglassDescription",
};

const traitsDescriptions = {
    aasimar: "PF2E.TraitDescriptionAasimar",
    aberration: "PF2E.TraitDescriptionAberration",
    abjuration: "PF2E.TraitDescriptionAbjuration",
    acid: "PF2E.TraitDescriptionAcid",
    additive1: "PF2E.TraitDescriptionAdditive",
    additive2: "PF2E.TraitDescriptionAdditive",
    additive3: "PF2E.TraitDescriptionAdditive",
    adjustment: "PF2E.TraitDescriptionAdjustment",
    aeon: "PF2E.TraitDescriptionAeon",
    aesir: "PF2E.TraitDescriptionAesir",
    aftermath: "PF2E.TraitDescriptionAftermath",
    agathion: "PF2E.TraitDescriptionAgathion",
    agile: "PF2E.TraitDescriptionAgile",
    air: "PF2E.TraitDescriptionAir",
    alchemical: "PF2E.TraitDescriptionAlchemical",
    alchemist: "PF2E.TraitDescriptionAlchemist",
    amphibious: "PF2E.TraitDescriptionAmphibious",
    anadi: "PF2E.TraitDescriptionAnadi",
    android: "PF2E.TraitDescriptionAndroid",
    apex: "PF2E.TraitDescriptionApex",
    aphorite: "PF2E.TraitDescriptionAphorite",
    arcane: "PF2E.TraitDescriptionArcane",
    archetype: "PF2E.TraitDescriptionArchetype",
    artifact: "PF2E.TraitDescriptionArtifact",
    attached: "PF2E.TraitDescriptionAttached",
    "attached-to-crossbow-or-firearm": "PF2E.TraitDescriptionAttached",
    "attached-to-shield": "PF2E.TraitDescriptionAttached",
    attack: "PF2E.TraitDescriptionAttack",
    auditory: "PF2E.TraitDescriptionAuditory",
    aura: "PF2E.TraitDescriptionAura",
    automaton: "PF2E.TraitDescriptionAutomaton",
    azarketi: "PF2E.TraitDescriptionAzarketi",
    backstabber: "PF2E.TraitDescriptionBackstabber",
    backswing: "PF2E.TraitDescriptionBackswing",
    barbarian: "PF2E.TraitDescriptionBarbarian",
    bard: "PF2E.TraitDescriptionBard",
    beastkin: "PF2E.TraitDescriptionBeastkin",
    bomb: "PF2E.TraitDescriptionBomb",
    brutal: "PF2E.TraitDescriptionBrutal",
    bulwark: "PF2E.TraitDescriptionBulwark",
    cantrip: "PF2E.TraitDescriptionCantrip",
    "capacity-3": "PF2E.TraitDescriptionCapacity",
    "capacity-4": "PF2E.TraitDescriptionCapacity",
    "capacity-5": "PF2E.TraitDescriptionCapacity",
    catalyst: "PF2E.TraitDescriptionCatalyst",
    catfolk: "PF2E.TraitDescriptionCatfolk",
    champion: "PF2E.TraitDescriptionChampion",
    changeling: "PF2E.TraitDescriptionChangeling",
    chaotic: "PF2E.TraitDescriptionChaotic",
    charm: "PF2E.TraitDescriptionCharm",
    class: "PF2E.TraitDescriptionClass",
    cleric: "PF2E.TraitDescriptionCleric",
    climbing: "PF2E.TraitDescriptionClimbing",
    clockwork: "PF2E.TraitDescriptionClockwork",
    cobbled: "PF2E.TraitDescriptionCobbled",
    cold: "PF2E.TraitDescriptionCold",
    combination: "PF2E.TraitDescriptionCombination",
    comfort: "PF2E.TraitDescriptionComfort",
    common: "PF2E.TraitDescriptionCommon",
    companion: "PF2E.TraitDescriptionCompanion",
    complex: "PF2E.TraitDescriptionComplex",
    composition: "PF2E.TraitDescriptionComposition",
    concealable: "PF2E.TraitDescriptionConcealable",
    concentrate: "PF2E.TraitDescriptionConcentrate",
    concussive: "PF2E.TraitDescriptionConcussive",
    conjuration: "PF2E.TraitDescriptionConjuration",
    conrasu: "PF2E.TraitDescriptionConrasu",
    consecration: "PF2E.TraitDescriptionConsecration",
    consumable: "PF2E.TraitDescriptionConsumable",
    contact: "PF2E.TraitDescriptionContact",
    contingency: "PF2E.TraitDescriptionContingency",
    contract: "PF2E.TraitDescriptionContract",
    "critical-fusion": "PF2E.TraitDescriptionCriticalFusion",
    curse: "PF2E.TraitDescriptionCurse",
    cursebound: "PF2E.TraitDescriptionCursebound",
    cursed: "PF2E.TraitDescriptionCursed",
    darkness: "PF2E.TraitDescriptionDarkness",
    darvakka: "PF2E.TraitDescriptionDarvakka",
    "deadly-2d10": "PF2E.TraitDescriptionDeadly",
    "deadly-2d12": "PF2E.TraitDescriptionDeadly",
    "deadly-2d8": "PF2E.TraitDescriptionDeadly",
    "deadly-3d10": "PF2E.TraitDescriptionDeadly",
    "deadly-3d12": "PF2E.TraitDescriptionDeadly",
    "deadly-3d8": "PF2E.TraitDescriptionDeadly",
    "deadly-4d10": "PF2E.TraitDescriptionDeadly",
    "deadly-4d12": "PF2E.TraitDescriptionDeadly",
    "deadly-4d8": "PF2E.TraitDescriptionDeadly",
    "deadly-d10": "PF2E.TraitDescriptionDeadly",
    "deadly-d12": "PF2E.TraitDescriptionDeadly",
    "deadly-d6": "PF2E.TraitDescriptionDeadly",
    "deadly-d8": "PF2E.TraitDescriptionDeadly",
    death: "PF2E.TraitDescriptionDeath",
    dedication: "PF2E.TraitDescriptionDedication",
    detection: "PF2E.TraitDescriptionDetection",
    deviant: "PF2E.TraitDescriptionDeviant",
    dhampir: "PF2E.TraitDescriptionDhampir",
    disarm: "PF2E.TraitDescriptionDisarm",
    disease: "PF2E.TraitDescriptionDisease",
    divination: "PF2E.TraitDescriptionDivination",
    divine: "PF2E.TraitDescriptionDivine",
    "double-barrel": "PF2E.TraitDescriptionDoubleBarrel",
    downtime: "PF2E.TraitDescriptionDowntime",
    drug: "PF2E.TraitDescriptionDrug",
    druid: "PF2E.TraitDescriptionDruid",
    duskwalker: "PF2E.TraitDescriptionDuskwalker",
    dwarf: "PF2E.TraitDescriptionDwarf",
    earth: "PF2E.TraitDescriptionEarth",
    eidolon: "PF2E.TraitDescriptionEidolon",
    electricity: "PF2E.TraitDescriptionElectricity",
    elf: "PF2E.TraitDescriptionElf",
    elixir: "PF2E.TraitDescriptionElixir",
    emotion: "PF2E.TraitDescriptionEmotion",
    enchantment: "PF2E.TraitDescriptionEnchantment",
    environment: "PF2E.TraitDescriptionEnvironment",
    esoterica: "PF2E.TraitDescriptionEsoterica",
    evil: "PF2E.TraitDescriptionEvil",
    evocation: "PF2E.TraitDescriptionEvocation",
    exploration: "PF2E.TraitDescriptionExploration",
    extradimensional: "PF2E.TraitDescriptionExtradimensional",
    "fatal-aim-d10": "PF2E.TraitDescriptionFatalAim",
    "fatal-aim-d12": "PF2E.TraitDescriptionFatalAim",
    "fatal-d10": "PF2E.TraitDescriptionFatal",
    "fatal-d12": "PF2E.TraitDescriptionFatal",
    "fatal-d8": "PF2E.TraitDescriptionFatal",
    fear: "PF2E.TraitDescriptionFear",
    fetchling: "PF2E.TraitDescriptionFetchling",
    fey: "PF2E.TraitDescriptionFey",
    fighter: "PF2E.TraitDescriptionFighter",
    finesse: "PF2E.TraitDescriptionFinesse",
    finisher: "PF2E.TraitDescriptionFinisher",
    fire: "PF2E.TraitDescriptionFire",
    fleshwarp: "PF2E.TraitDescriptionFleshwarp",
    flexible: "PF2E.TraitDescriptionFlexible",
    flourish: "PF2E.TraitDescriptionFlourish",
    focused: "PF2E.TraitDescriptionFocused",
    force: "PF2E.TraitDescriptionForce",
    forceful: "PF2E.TraitDescriptionForceful",
    fortune: "PF2E.TraitDescriptionFortune",
    "free-hand": "PF2E.TraitDescriptionFreeHand",
    fulu: "PF2E.TraitDescriptionFulu",
    fungus: "PF2E.TraitDescriptionFungus",
    gadget: "PF2E.TraitDescriptionGadget",
    ganzi: "PF2E.TraitDescriptionGanzi",
    general: "PF2E.TraitDescriptionGeneral",
    genie: "PF2E.TraitDescriptionGenie",
    geniekin: "PF2E.TraitDescriptionGeniekin",
    ghoran: "PF2E.TraitDescriptionGhoran",
    ghul: "PF2E.TraitDescriptionGhul",
    gnoll: "PF2E.TraitDescriptionGnoll",
    gnome: "PF2E.TraitDescriptionGnome",
    goblin: "PF2E.TraitDescriptionGoblin",
    goloma: "PF2E.TraitDescriptionGoloma",
    good: "PF2E.TraitDescriptionGood",
    grapple: "PF2E.TraitDescriptionGrapple",
    grimoire: "PF2E.TraitDescriptionGrimoire",
    grippli: "PF2E.TraitDescriptionGrippli",
    gunslinger: "PF2E.TraitDescriptionGunslinger",
    halfling: "PF2E.TraitDescriptionHalfling",
    "half-elf": "PF2E.TraitDescriptionHalfElf",
    "half-orc": "PF2E.TraitDescriptionHalfOrc",
    "jousting-d6": "PF2E.TraitDescriptionJousting",
    hampering: "PF2E.TraitDescriptionHampering",
    haunt: "PF2E.TraitDescriptionHaunt",
    healing: "PF2E.TraitDescriptionHealing",
    hex: "PF2E.TraitDescriptionHex",
    hobgoblin: "PF2E.TraitDescriptionHobgoblin",
    human: "PF2E.TraitDescriptionHuman",
    humanoid: "PF2E.TraitDescriptionHumanoid",
    ifrit: "PF2E.TraitDescriptionIfrit",
    illusion: "PF2E.TraitDescriptionIllusion",
    incapacitation: "PF2E.TraitDescriptionIncapacitation",
    incarnate: "PF2E.TraitDescriptionIncarnate",
    incorporeal: "PF2E.TraitDescriptionIncorporeal",
    infused: "PF2E.TraitDescriptionInfused",
    ingested: "PF2E.TraitDescriptionIngested",
    inhaled: "PF2E.TraitDescriptionInhaled",
    injection: "PF2E.TraitDescriptionInjection",
    injury: "PF2E.TraitDescriptionInjury",
    intelligent: "PF2E.TraitDescriptionIntelligent",
    inventor: "PF2E.TraitDescriptionInventor",
    invested: "PF2E.TraitDescriptionInvested",
    investigator: "PF2E.TraitDescriptionInvestigator",
    kashrishi: "PF2E.TraitDescriptionKashrishi",
    kickback: "PF2E.TraitDescriptionKickback",
    kitsune: "TraitDescriptionKitsune",
    kobold: "TraitDescriptionKobold",
    lawful: "PF2E.TraitDescriptionLawful",
    leshy: "PF2E.TraitDescriptionLeshy",
    light: "PF2E.TraitDescriptionLight",
    linguistic: "PF2E.TraitDescriptionLinguistic",
    litany: "PF2E.TraitDescriptionLitany",
    lizardfolk: "PF2E.TraitDescriptionLizardfolk",
    magical: "PF2E.TraitDescriptionMagical",
    magus: "PF2E.TraitDescriptionMagus",
    manipulate: "PF2E.TraitDescriptionManipulate",
    mechanical: "PF2E.TraitDescriptionMechanical",
    mental: "PF2E.TraitDescriptionMental",
    metal: "PF2E.TraitDescriptionMetal",
    metamagic: "PF2E.TraitDescriptionMetamagic",
    mindless: "PF2E.TraitDescriptionMindless",
    minion: "PF2E.TraitDescriptionMinion",
    misfortune: "PF2E.TraitDescriptionMisfortune",
    modification: "PF2E.TraitDescriptionModification",
    modular: "PF2E.TraitDescriptionModular",
    monk: "PF2E.TraitDescriptionMonk",
    morph: "PF2E.TraitDescriptionMorph",
    mounted: "PF2E.TraitDescriptionMounted",
    move: "PF2E.TraitDescriptionMove",
    multiclass: "PF2E.TraitDescriptionMulticlass",
    mutagen: "PF2E.TraitDescriptionMutagen",
    nagaji: "PF2E.TraitDescriptionNagaji",
    necromancy: "PF2E.TraitDescriptionNecromancy",
    negative: "PF2E.TraitDescriptionNegative",
    noisy: "PF2E.TraitDescriptionNoisy",
    nonlethal: "PF2E.TraitDescriptionNonlethal",
    oath: "PF2E.TraitDescriptionOath",
    occult: "PF2E.TraitDescriptionOccult",
    oil: "PF2E.TraitDescriptionOil",
    olfactory: "PF2E.TraitDescriptionOlfactory",
    open: "PF2E.TraitDescriptionOpen",
    oracle: "PF2E.TraitDescriptionOracle",
    orc: "PF2E.TraitDescriptionOrc",
    oread: "PF2E.TraitDescriptionOread",
    parry: "PF2E.TraitDescriptionParry",
    peachwood: "PF2E.PreciousMaterialPeachwoodDescription",
    plant: "PF2E.TraitDescriptionPlant",
    poison: "PF2E.TraitDescriptionPoison",
    polymorph: "PF2E.TraitDescriptionPolymorph",
    poppet: "PF2E.TraitDescriptionPoppet",
    portable: "PF2E.TraitDescriptionPortable",
    positive: "PF2E.TraitDescriptionPositive",
    possession: "PF2E.TraitDescriptionPossession",
    potion: "PF2E.TraitDescriptionPotion",
    precious: "PF2E.TraitDescriptionPrecious",
    prediction: "PF2E.TraitDescriptionPrediction",
    press: "PF2E.TraitDescriptionPress",
    primal: "PF2E.TraitDescriptionPrimal",
    propulsive: "PF2E.TraitDescriptionPropulsive",
    psyche: "PF2E.TraitDescriptionPsyche",
    psychic: "PF2E.TraitDescriptionPsychic",
    rage: "PF2E.TraitDescriptionRage",
    ranger: "PF2E.TraitDescriptionRanger",
    ...rangeDescriptions,
    "ranged-trip": "PF2E.TraitDescriptionRangedTrip",
    rare: "PF2E.TraitDescriptionRare",
    ratfolk: "PF2E.TraitDescriptionRatfolk",
    reach: "PF2E.TraitDescriptionReach",
    "reach-0": "PF2E.TraitDescriptionReach",
    "reach-10": "PF2E.TraitDescriptionReach",
    "reach-100": "PF2E.TraitDescriptionReach",
    "reach-1000": "PF2E.TraitDescriptionReach",
    "reach-15": "PF2E.TraitDescriptionReach",
    "reach-20": "PF2E.TraitDescriptionReach",
    "reach-25": "PF2E.TraitDescriptionReach",
    "reach-30": "PF2E.TraitDescriptionReach",
    "reach-40": "PF2E.TraitDescriptionReach",
    "reach-50": "PF2E.TraitDescriptionReach",
    "reach-60": "PF2E.TraitDescriptionReach",
    reflection: "PF2E.TraitDescriptionReflection",
    reload: "PF2E.TraitDescriptionReload",
    "reload-0": "PF2E.TraitDescriptionReload",
    "reload-1": "PF2E.TraitDescriptionReload",
    "reload-1-min": "PF2E.TraitDescriptionReload",
    "reload-2": "PF2E.TraitDescriptionReload",
    repeating: "PF2E.TraitDescriptionRepeating",
    resonant: "PF2E.TraitDescriptionResonant",
    revelation: "PF2E.TraitDescriptionRevelation",
    rogue: "PF2E.TraitDescriptionRogue",
    saggorak: "PF2E.TraitDescriptionSaggorak",
    "scatter-10": "PF2E.TraitDescriptionScatter",
    "scatter-15": "PF2E.TraitDescriptionScatter",
    "scatter-5": "PF2E.TraitDescriptionScatter",
    scroll: "PF2E.TraitDescriptionScroll",
    scrying: "PF2E.TraitDescriptionScrying",
    secret: "PF2E.TraitDescriptionSecret",
    shadow: "PF2E.TraitDescriptionShadow",
    shisk: "PF2E.TraitDescriptionShisk",
    shoony: "PF2E.TraitDescriptionShoony",
    shove: "PF2E.TraitDescriptionShove",
    skeleton: "PF2E.TraitDescriptionSkeleton",
    skill: "PF2E.TraitDescriptionSkill",
    sleep: "PF2E.TraitDescriptionSleep",
    snare: "PF2E.TraitDescriptionSnare",
    social: "PF2E.TraitDescriptionSocial",
    sonic: "PF2E.TraitDescriptionSonic",
    sorcerer: "PF2E.TraitDescriptionSorcerer",
    spellheart: "PF2E.TraitDescriptionSpellheart",
    spellshot: "PF2E.TraitNoDescription",
    splash: "PF2E.TraitDescriptionSplash",
    "splash-10": "PF2E.TraitDescriptionSplash10",
    sprite: "PF2E.TraitDescriptionSprite",
    staff: "PF2E.TraitDescriptionStaff",
    stance: "PF2E.TraitDescriptionStance",
    steam: "PF2E.TraitDescriptionSteam",
    strix: "PF2E.TraitDescriptionStrix",
    structure: "PF2E.TraitDescriptionStructure",
    suli: "PF2E.TraitDescriptionSuli",
    summon: "PF2E.TraitDescriptionSummon",
    summoned: "PF2E.TraitDescriptionSummoned",
    summoner: "PF2E.TraitDescriptionSummoner",
    swashbuckler: "PF2E.TraitDescriptionSwashbuckler",
    sweep: "PF2E.TraitDescriptionSweep",
    sylph: "PF2E.TraitDescriptionSylph",
    talisman: "PF2E.TraitDescriptionTalisman",
    tattoo: "PF2E.TraitDescriptionTattoo",
    tech: "PF2E.TraitDescriptionTech",
    telepathy: "PF2E.TraitDescriptionTelepathy",
    teleportation: "PF2E.TraitDescriptionTeleportation",
    tengu: "PF2E.TraitDescriptionTengu",
    tethered: "PF2E.TraitDescriptionTethered",
    thaumaturge: "PF2E.TraitDescriptionThaumaturge",
    thrown: "PF2E.TraitDescriptionThrown",
    "thrown-10": "PF2E.TraitDescriptionThrown",
    "thrown-100": "PF2E.TraitDescriptionThrown",
    "thrown-15": "PF2E.TraitDescriptionThrown",
    "thrown-20": "PF2E.TraitDescriptionThrown",
    "thrown-200": "PF2E.TraitDescriptionThrown",
    "thrown-25": "PF2E.TraitDescriptionThrown",
    "thrown-30": "PF2E.TraitDescriptionThrown",
    "thrown-40": "PF2E.TraitDescriptionThrown",
    "thrown-50": "PF2E.TraitDescriptionThrown",
    "thrown-60": "PF2E.TraitDescriptionThrown",
    "thrown-80": "PF2E.TraitDescriptionThrown",
    tiefling: "PF2E.TraitDescriptionTiefling",
    time: "PF2E.TraitDescriptionTime",
    transmutation: "PF2E.TraitDescriptionTransmutation",
    trap: "PF2E.TraitDescriptionTrap",
    trip: "PF2E.TraitDescriptionTrip",
    "true-name": "PF2E.TraitDescriptionTrueName",
    twin: "PF2E.TraitDescriptionTwin",
    "two-hand-d10": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d12": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d6": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d8": "PF2E.TraitDescriptionTwoHand",
    unarmed: "PF2E.TraitDescriptionUnarmed",
    uncommon: "PF2E.TraitDescriptionUncommon",
    undine: "PF2E.TraitDescriptionUndine",
    unique: "PF2E.TraitDescriptionUnique",
    unstable: "PF2E.TraitDescriptionUnstable",
    vanara: "PF2E.TraitDescriptionVanara",
    vishkanya: "PF2E.TraitDescriptionVishkanya",
    "versatile-acid": "PF2E.TraitDescriptionVersatile",
    "versatile-b": "PF2E.TraitDescriptionVersatile",
    "versatile-chaotic": "PF2E.TraitDescriptionVersatile",
    "versatile-cold": "PF2E.TraitDescriptionVersatile",
    "versatile-electricity": "PF2E.TraitDescriptionVersatile",
    "versatile-evil": "PF2E.TraitDescriptionVersatile",
    "versatile-fire": "PF2E.TraitDescriptionVersatile",
    "versatile-force": "PF2E.TraitDescriptionVersatile",
    "versatile-good": "PF2E.TraitDescriptionVersatile",
    "versatile-lawful": "PF2E.TraitDescriptionVersatile",
    "versatile-negative": "PF2E.TraitDescriptionVersatile",
    "versatile-p": "PF2E.TraitDescriptionVersatile",
    "versatile-positive": "PF2E.TraitDescriptionVersatile",
    "versatile-s": "PF2E.TraitDescriptionVersatile",
    "versatile-sonic": "PF2E.TraitDescriptionVersatile",
    virulent: "PF2E.TraitDescriptionVirulent",
    visual: "PF2E.TraitDescriptionVisual",
    "volley-20": "PF2E.TraitDescriptionVolley",
    "volley-30": "PF2E.TraitDescriptionVolley",
    "volley-50": "PF2E.TraitDescriptionVolley",
    wand: "PF2E.TraitDescriptionWand",
    water: "PF2E.TraitDescriptionWater",
    witch: "PF2E.TraitDescriptionWitch",
    wizard: "PF2E.TraitDescriptionWizard",
    ...preciousMaterialDescriptions,
};

const preciousMaterialGrades: Record<PreciousMaterialGrade, string> = {
    low: "PF2E.PreciousMaterialLowGrade",
    standard: "PF2E.PreciousMaterialStandardGrade",
    high: "PF2E.PreciousMaterialHighGrade",
};

const meleeWeaponGroups: Record<MeleeWeaponGroup, string> = {
    axe: "PF2E.WeaponGroupAxe",
    brawling: "PF2E.WeaponGroupBrawling",
    club: "PF2E.WeaponGroupClub",
    dart: "PF2E.WeaponGroupDart",
    flail: "PF2E.WeaponGroupFlail",
    hammer: "PF2E.WeaponGroupHammer",
    knife: "PF2E.WeaponGroupKnife",
    pick: "PF2E.WeaponGroupPick",
    polearm: "PF2E.WeaponGroupPolearm",
    shield: "PF2E.WeaponGroupShield",
    spear: "PF2E.WeaponGroupSpear",
    sword: "PF2E.WeaponGroupSword",
};

const weaponGroups: Record<WeaponGroup, string> = {
    ...meleeWeaponGroups,
    bomb: "PF2E.WeaponGroupBomb",
    bow: "PF2E.WeaponGroupBow",
    firearm: "PF2E.WeaponGroupFirearm",
    sling: "PF2E.WeaponGroupSling",
};

// Creature and Equipment Sizes
const sizeTypes: Record<Size, string> = {
    tiny: "PF2E.ActorSizeTiny",
    sm: "PF2E.ActorSizeSmall",
    med: "PF2E.ActorSizeMedium",
    lg: "PF2E.ActorSizeLarge",
    huge: "PF2E.ActorSizeHuge",
    grg: "PF2E.ActorSizeGargantuan",
};

const featTypes: Record<FeatType, string> = {
    ancestry: "PF2E.FeatTypeAncestry",
    ancestryfeature: "PF2E.FeatTypeAncestryfeature",
    class: "PF2E.FeatTypeClass",
    classfeature: "PF2E.FeatTypeClassfeature",
    skill: "PF2E.FeatTypeSkill",
    general: "PF2E.FeatTypeGeneral",
    archetype: "PF2E.FeatTypeArchetype",
    bonus: "PF2E.FeatTypeBonus",
    pfsboon: "PF2E.FeatPFSBoonHeader",
    deityboon: "PF2E.FeatDeityBoonHeader",
    curse: "PF2E.FeatCurseHeader",
};

const alignments: Record<Alignment, string> = {
    LG: "PF2E.AlignmentLG",
    NG: "PF2E.AlignmentNG",
    CG: "PF2E.AlignmentCG",
    LN: "PF2E.AlignmentLN",
    N: "PF2E.AlignmentN",
    CN: "PF2E.AlignmentCN",
    LE: "PF2E.AlignmentLE",
    NE: "PF2E.AlignmentNE",
    CE: "PF2E.AlignmentCE",
};

const deityDomains = Object.keys(enJSON.PF2E.Item.Deity.Domain).reduce((domains, key) => {
    const slug = sluggify(key);
    const casedKey = sluggify(key, { camel: "bactrian" });
    return {
        ...domains,
        [slug]: {
            label: `PF2E.Item.Deity.Domain.${casedKey}.Label`,
            description: `PF2E.Item.Deity.Domain.${casedKey}.Description`,
        },
    };
}, {} as Record<DeityDomain, { label: string; description: string }>);

const weaponReload: Record<WeaponReloadTime, string> = {
    "-": "—", // Reload value for thrown weapons
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    10: "PF2E.Item.Weapon.ReloadOneMinute",
};

export const PF2ECONFIG = {
    chatDamageButtonShieldToggle: false,

    statusEffects: {
        lastIconTheme: "default" as StatusEffectIconTheme,
        iconDir: "systems/pf2e/icons/conditions/",
        conditions: tokenHUDConditions,
    },

    levels: {
        1: "PF2E.Level1",
        2: "PF2E.Level2",
        3: "PF2E.Level3",
        4: "PF2E.Level4",
        5: "PF2E.Level5",
        6: "PF2E.Level6",
        7: "PF2E.Level7",
        8: "PF2E.Level8",
        9: "PF2E.Level9",
        10: "PF2E.Level10",
        11: "PF2E.Level11",
        12: "PF2E.Level12",
        13: "PF2E.Level13",
        14: "PF2E.Level14",
        15: "PF2E.Level15",
        16: "PF2E.Level16",
        17: "PF2E.Level17",
        18: "PF2E.Level18",
        19: "PF2E.Level19",
        20: "PF2E.Level20",
    },

    abilities: {
        str: "PF2E.AbilityStr",
        dex: "PF2E.AbilityDex",
        con: "PF2E.AbilityCon",
        int: "PF2E.AbilityInt",
        wis: "PF2E.AbilityWis",
        cha: "PF2E.AbilityCha",
    },

    attributes: {
        perception: "PF2E.PerceptionLabel",
        stealth: "PF2E.StealthLabel",
        initiative: "PF2E.PerceptionLabel",
    },

    dcAdjustments: {
        "incredibly easy": "PF2E.DCAdjustmentIncrediblyEasy",
        "very easy": "PF2E.DCAdjustmentVeryEasy",
        easy: "PF2E.DCAdjustmentEasy",
        normal: "PF2E.DCAdjustmentNormal",
        hard: "PF2E.DCAdjustmentHard",
        "very hard": "PF2E.DCAdjustmentVeryHard",
        "incredibly hard": "PF2E.DCAdjustmentIncrediblyHard",
    },

    skills: {
        acr: "PF2E.SkillAcr",
        arc: "PF2E.SkillArc",
        ath: "PF2E.SkillAth",
        cra: "PF2E.SkillCra",
        dec: "PF2E.SkillDec",
        dip: "PF2E.SkillDip",
        itm: "PF2E.SkillItm",
        med: "PF2E.SkillMed",
        nat: "PF2E.SkillNat",
        occ: "PF2E.SkillOcc",
        prf: "PF2E.SkillPrf",
        rel: "PF2E.SkillRel",
        soc: "PF2E.SkillSoc",
        ste: "PF2E.SkillSte",
        sur: "PF2E.SkillSur",
        thi: "PF2E.SkillThi",
    },

    martialSkills: {
        unarmored: "PF2E.MartialUnarmored",
        light: "PF2E.MartialLight",
        medium: "PF2E.MartialMedium",
        heavy: "PF2E.MartialHeavy",
        simple: "PF2E.MartialSimple",
        martial: "PF2E.MartialMartial",
        advanced: "PF2E.MartialAdvanced",
        unarmed: "PF2E.MartialUnarmed",
    },

    saves: {
        fortitude: "PF2E.SavesFortitude",
        reflex: "PF2E.SavesReflex",
        will: "PF2E.SavesWill",
    },

    savingThrowDefaultAbilities: {
        fortitude: "con",
        reflex: "dex",
        will: "wis",
    } as const,

    currencies: {
        pp: "PF2E.CurrencyPP",
        gp: "PF2E.CurrencyGP",
        sp: "PF2E.CurrencySP",
        cp: "PF2E.CurrencyCP",
    },

    preciousMaterialGrades,
    preciousMaterials,

    armorPotencyRunes: {
        "1": "PF2E.ArmorPotencyRune1",
        "2": "PF2E.ArmorPotencyRune2",
        "3": "PF2E.ArmorPotencyRune3",
        "4": "PF2E.ArmorPotencyRune4",
    },

    armorResiliencyRunes: {
        resilient: "PF2E.ArmorResilientRune",
        greaterResilient: "PF2E.ArmorGreaterResilientRune",
        majorResilient: "PF2E.ArmorMajorResilientRune",
    },
    armorPropertyRunes: {
        ready: "PF2E.ArmorPropertyRuneReady",
        slick: "PF2E.ArmorPropertyRuneSlick",
        shadow: "PF2E.ArmorPropertyRuneShadow",
        glamered: "PF2E.ArmorPropertyRuneGlamered",
        acidResistant: "PF2E.ArmorPropertyRuneAcidResistant",
        coldResistant: "PF2E.ArmorPropertyRuneColdResistant",
        electricityResistant: "PF2E.ArmorPropertyRuneElectricityResistant",
        fireResistant: "PF2E.ArmorPropertyRuneFireResistant",
        greaterSlick: "PF2E.ArmorPropertyRuneGreaterSlick",
        invisibility: "PF2E.ArmorPropertyRuneInvisibility",
        sinisterKnight: "PF2E.ArmorPropertyRuneSinisterKnight",
        greaterDread: "PF2E.ArmorPropertyRuneGreaterDread",
        greaterReady: "PF2E.ArmorPropertyRuneGreaterReady",
        greaterShadow: "PF2E.ArmorPropertyRuneGreaterShadow",
        greaterInvisibility: "PF2E.ArmorPropertyRuneGreaterInvisibility",
        greaterAcidResistant: "PF2E.ArmorPropertyRuneGreaterAcidResistant",
        greaterColdResistant: "PF2E.ArmorPropertyRuneGreaterColdResistant",
        greaterElectricityResistant: "PF2E.ArmorPropertyRuneGreaterElectricityResistant",
        greaterFireResistant: "PF2E.ArmorPropertyRuneGreaterFireResistant",
        fortification: "PF2E.ArmorPropertyRuneFortification",
        winged: "PF2E.ArmorPropertyRuneWinged",
        rockBraced: "PF2E.ArmorPropertyRuneRockBraced",
        soaring: "PF2E.ArmorPropertyRuneSoaring",
        antimagic: "PF2E.ArmorPropertyRuneAntimagic",
        majorSlick: "PF2E.ArmorPropertyRuneMajorSlick",
        ethereal: "PF2E.ArmorPropertyRuneEthereal",
        majorShadow: "PF2E.ArmorPropertyRuneMajorShadow",
        moderateDread: "PF2E.ArmorPropertyRuneModerateDread",
        greaterFortification: "PF2E.ArmorPropertyRuneGreaterFortification",
        greaterWinged: "PF2E.ArmorPropertyRuneGreaterWinged",
        deathless: "PF2E.ArmorPropertyRuneDeathless",
        dread: "PF2E.ArmorPropertyRuneDread",
        bitter: "PF2E.ArmorPropertyRuneBitter",
        stanching: "PF2E.ArmorPropertyRuneStanching",
        greaterStanching: "PF2E.ArmorPropertyRuneGreaterStanching",
        majorStanching: "PF2E.ArmorPropertyRuneMajorStanching",
        trueStanching: "PF2E.ArmorPropertyRuneTrueStanching",
        implacable: "PF2E.ArmorPropertyRuneImplacable",
    },
    accessoryPropertyRunes: {
        called: "PF2E.AccessoryPropertyRuneCalled",
        dragonsBreath: "PF2E.AccessoryPropertyRuneDragonsBreath",
        paired: "PF2E.AccessoryPropertyRunePaired",
        greaterPaired: "PF2E.AccessoryPropertyRuneGreaterPaired",
        majorPaired: "PF2E.AccessoryPropertyRuneMajorPaired",
        presentable: "PF2E.AccessoryPropertyRunePresentable",
        snagging: "PF2E.AccessoryPropertyRuneSnagging",
        softLanding: "PF2E.AccessoryPropertyRuneSoftLanding",
        spellBastion: "PF2E.AccessoryPropertyRuneSpellBastion",
        windCatcher: "PF2E.AccessoryPropertyRuneWindCatcher",
        greaterWindCatcher: "PF2E.AccessoryPropertyRuneGreaterWindCatcher",
    },
    weaponPotencyRunes: {
        1: "PF2E.WeaponPotencyRune1",
        2: "PF2E.WeaponPotencyRune2",
        3: "PF2E.WeaponPotencyRune3",
        4: "PF2E.WeaponPotencyRune4",
    },
    weaponStrikingRunes: {
        striking: "PF2E.ArmorStrikingRune",
        greaterStriking: "PF2E.ArmorGreaterStrikingRune",
        majorStriking: "PF2E.ArmorMajorStrikingRune",
    },
    weaponPropertyRunes,
    damageTraits,
    damageTypes,
    damageRollFlavors,
    damageCategories,
    materialDamageEffects,
    resistanceTypes,

    stackGroups: {
        arrows: "PF2E.StackGroupArrows",
        bolts: "PF2E.StackGroupBolts",
        slingBullets: "PF2E.StackGroupSlingBullets",
        blowgunDarts: "PF2E.StackGroupBlowgunDarts",
        woodenTaws: "PF2E.StackGroupWoodenTaws",
        rounds5: "PF2E.StackGroupRounds5",
        rounds10: "PF2E.StackGroupRounds10",
        rations: "PF2E.StackGroupRations",
        coins: "PF2E.StackGroupCoins",
        gems: "PF2E.StackGroupGems",
        sacks: "PF2E.StackGroupSacks",
    },

    weaknessTypes,

    weaponDamage: {
        bludgeoning: "PF2E.TraitBludgeoning",
        piercing: "PF2E.TraitPiercing",
        slashing: "PF2E.TraitSlashing",
        modular: "PF2E.TraitModular",
    },

    healingTypes: {
        healing: "PF2E.TraitHealing",
        temphp: "PF2E.HealingTypeTemporaryHealing",
    },

    weaponCategories,
    weaponGroups,
    meleeWeaponGroups,

    baseWeaponTypes,
    equivalentWeapons,

    weaponDescriptions: {
        club: "PF2E.WeaponDescriptionClub",
        knife: "PF2E.WeaponDescriptionKnife",
        brawling: "PF2E.WeaponDescriptionBrawling",
        spear: "PF2E.WeaponDescriptionSpear",
        sword: "PF2E.WeaponDescriptionSword",
        axe: "PF2E.WeaponDescriptionAxe",
        flail: "PF2E.WeaponDescriptionFlail",
        polearm: "PF2E.WeaponDescriptionPolearm",
        pick: "PF2E.WeaponDescriptionPick",
        hammer: "PF2E.WeaponDescriptionHammer",
        shield: "PF2E.WeaponDescriptionShield",
        dart: "PF2E.WeaponDescriptionDart",
        bow: "PF2E.WeaponDescriptionBow",
        sling: "PF2E.WeaponDescriptionSling",
        bomb: "PF2E.WeaponDescriptionBomb",
    },

    usageTraits: {
        "affixed-to-a-ranged-weapon": "PF2E.TraitAffixedToARangedWeapon",
        "affixed-to-a-shield": "PF2E.TraitAffixedToAShield",
        "affixed-to-a-two-handed-firearm-or-crossbow": "PF2E.TraitAffixededToATwoHandedFirearmOrCrossbow",
        "affixed-to-armor": "PF2E.TraitAffixedToArmor",
        "affixed-to-medium-heavy-armor": "PF2E.TraitAffixedToMediumHeavyArmor",
        "affixed-to-armor-or-a-weapon": "PF2E.TraitAffixedToArmorOrAWeapon",
        "affixed-to-armor-or-travelers-clothing": "PF2E.TraitAffixedToArmorOrTravelersClothing",
        "affixed-to-crossbow-or-firearm": "PF2E.TraitAffixededToCrossbowOrFirearm",
        "affixed-to-firearm": "PF2E.TraitAffixededToFirearm",
        "affixed-to-firearm-with-a-reload-of-1": "PF2E.TraitAffixededToFirearmWithAReloadOf1",
        "affixed-to-firearm-with-the-kickback-trait": "PF2E.TraitAffixededToFirearmWithTheKickbackTrait",
        "affixed-to-headgear": "PF2E.TraitAffixedToHeadgear",
        "affixed-to-weapon": "PF2E.TraitAffixedToWeapon",
        "applied-to-a-wind-powered-vehicle": "PF2E.TraitAppliedToAWindPoweredVehicle",
        "applied-to-any-item-of-light-or-negligible-bulk": "PF2E.TraitAppliedToAnyItemOfLightOrNegligibleBulk",
        "applied-to-any-visible-article-of-clothing": "PF2E.TraitAppliedToAnyVisibleArticleOfClothing",
        "applied-to-belt-cape-cloak-or-scarf": "PF2E.TraitAppliedToBeltCapeCloakOrScarf",
        "applied-to-boots-cape-cloak-or-umbrella": "PF2E.TraitAppliedToBootsCapeCloakOrUmbrella",
        "applied-to-dueling-cape-or-shield": "PF2E.TraitAppliedToDuelingCapeOrShield",
        "applied-to-buckler-shield": "PF2E.TraitAppliedToBucklerShield",
        "applied-to-shield": "PF2E.TraitAppliedToShield",
        "attached-to-a-thrown-weapon": "PF2E.TraitAttachedToAThrownWeapon",
        "attached-to-crossbow-or-firearm": "PF2E.TraitAttachedToCrossbowOrFirearm",
        "attached-to-crossbow-or-firearm-firing-mechanism": "PF2E.TraitAttachedToCrossbowOrFirearmFiringMechanism",
        "attached-to-crossbow-or-firearm-scope": "PF2E.TraitAttachedToCrossbowOrFirearmScope",
        "attached-to-firearm": "PF2E.TraitAttachedToFirearm",
        "attached-to-firearm-scope": "PF2E.TraitAttachedToFirearmScope",
        bonded: "PF2E.TraitBonded",
        "each-rune-applied-to-a-separate-item-that-has-pockets":
            "PF2E.TraitEachRuneAppliedToASeparateItemThatHasPockets",
        "etched-onto-a-weapon": "PF2E.TraitEtchedOntoAWeapon",
        "etched-onto-armor": "PF2E.TraitEtchedOntoArmor",
        "etched-onto-clan-dagger": "PF2E.TraitEtchedOntoAClanDagger",
        "etched-onto-lm-nonmetal-armor": "PF2E.TraitEtchedOntoLightMedNMArmor",
        "etched-onto-med-heavy-armor": "PF2E.TraitEtchedOntoMedHeavyArmor",
        "etched-onto-melee-weapon": "PF2E.TraitEtchedOntoAMeleeWeapon",
        "etched-onto-thrown-weapon": "PF2E.TraitEtchedOntoAThrownWeapon",
        "held-in-one-hand": "PF2E.TraitHeldOneHand",
        "held-in-two-hands": "PF2E.TraitHeldTwoHands",
        other: "Other",
        "sewn-into-clothing": "PF2E.TraitSewnIntoClothing",
        "tattooed-on-the-body": "PF2E.TraitTattooedOnTheBody",
        worn: "PF2E.TraitWorn",
        wornamulet: "PF2E.TraitWornAmulet",
        wornanklets: "PF2E.TraitWornAnklets",
        wornarmbands: "PF2E.TraitWornArmbands",
        wornbackpack: "PF2E.TraitWornBackpack",
        wornbarding: "PF2E.TraitWornBarding",
        wornbelt: "PF2E.TraitWornBelt",
        wornbeltpouch: "PF2E.TraitWornBeltPouch",
        wornbracelet: "PF2E.TraitWornBracelet",
        wornbracers: "PF2E.TraitWornBracers",
        worncirclet: "PF2E.TraitWornCirclet",
        worncloak: "PF2E.TraitWornCloak",
        wornclothing: "PF2E.TraitWornClothing",
        worncollar: "PF2E.TraitWornCollar",
        worncrown: "PF2E.TraitWornCrown",
        wornepaulet: "PF2E.TraitWornEpaulet",
        worneyepiece: "PF2E.TraitWornEyepiece",
        worngarment: "PF2E.TraitWornGarment",
        worngloves: "PF2E.TraitWornGloves",
        wornheadwear: "PF2E.TraitWornHeadwear",
        wornhorseshoes: "PF2E.TraitWornHorseshoes",
        wornmask: "PF2E.TraitWornMask",
        wornnecklace: "PF2E.TraitWornNecklace",
        wornonbelt: "PF2E.TraitWornOnBelt",
        wornoronehand: "PF2E.TraitWornOrOneHand",
        wornring: "PF2E.TraitWornRing",
        wornsaddle: "PF2E.TraitWornSaddle",
        wornshoes: "PF2E.TraitWornShoes",
        wornwrist: "PF2E.TraitWornOnWrists",
        "worn-and-attached-to-two-weapons": "PF2E.TraitWornAndAttachedToTwoWeapons",
        "worn-under-armor": "PF2E.TraitWornUnderArmor",
    },

    rarityTraits: {
        common: "PF2E.TraitCommon",
        uncommon: "PF2E.TraitUncommon",
        rare: "PF2E.TraitRare",
        unique: "PF2E.TraitUnique",
    },

    magicTraditions,
    spellOtherTraits,

    magicSchools,
    classTraits,
    ancestryTraits,
    ancestryItemTraits,
    deityDomains,

    weaponTraits,
    otherWeaponTags,

    armorTraits,
    otherArmorTags,

    equipmentTraits,

    consumableTraits,
    otherConsumableTags,

    actionTraits,
    spellTraits,
    featTraits,
    creatureTraits,
    monsterTraits: creatureTraits,
    npcAttackTraits,
    hazardTraits,
    vehicleTraits,

    traitsDescriptions,

    weaponHands: {
        1: "PF2E.WeaponHands1",
        "1+": "PF2E.WeaponHands1Plus",
        2: "PF2E.WeaponHands2",
    },

    itemBonuses: {
        "-2": "PF2E.ItemBonusMinus2",
        0: "PF2E.ItemBonus0",
        1: "PF2E.ItemBonus1",
        2: "PF2E.ItemBonus2",
        3: "PF2E.ItemBonus3",
    },

    damageDice: {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
    },

    damageDie: {
        d4: "PF2E.DamageDieD4",
        d6: "PF2E.DamageDieD6",
        d8: "PF2E.DamageDieD8",
        d10: "PF2E.DamageDieD10",
        d12: "PF2E.DamageDieD12",
    },

    weaponMAP: {
        1: "-1/-2",
        2: "-2/-4",
        3: "-3/-6",
        4: "-4/-8",
        5: "-5/-10",
    },

    weaponReload,

    armorTypes: {
        unarmored: "PF2E.ArmorTypeUnarmored",
        light: "PF2E.ArmorTypeLight",
        medium: "PF2E.ArmorTypeMedium",
        heavy: "PF2E.ArmorTypeHeavy",
        shield: "PF2E.ArmorTypeShield",
    },

    armorGroups: {
        composite: "PF2E.ArmorGroupComposite",
        chain: "PF2E.ArmorGroupChain",
        cloth: "PF2E.ArmorGroupCloth",
        leather: "PF2E.ArmorGroupLeather",
        plate: "PF2E.ArmorGroupPlate",
    },

    consumableTypes: {
        ammo: "PF2E.ConsumableTypeAmmo",
        catalyst: "PF2E.TraitCatalyst",
        drug: "PF2E.ConsumableTypeDrug",
        elixir: "PF2E.ConsumableTypeElixir",
        fulu: "PF2E.TraitFulu",
        gadget: "PF2E.TraitGadget",
        oil: "PF2E.ConsumableTypeOil",
        other: "PF2E.ConsumableTypeOther",
        mutagen: "PF2E.ConsumableTypeMutagen",
        poison: "PF2E.ConsumableTypePoison",
        potion: "PF2E.ConsumableTypePotion",
        scroll: "PF2E.ConsumableTypeScroll",
        snare: "PF2E.ConsumableTypeSnare",
        talisman: "PF2E.ConsumableTypeTalisman",
        tool: "PF2E.ConsumableTypeTool",
        wand: "PF2E.ConsumableTypeWand",
    },

    preparationType: {
        prepared: "PF2E.PreparationTypePrepared",
        spontaneous: "PF2E.PreparationTypeSpontaneous",
        innate: "PF2E.PreparationTypeInnate",
        focus: "PF2E.SpellCategoryFocus",
        ritual: "PF2E.SpellCategoryRitual",
        items: "PF2E.PreparationTypeItems",
    },

    areaTypes: {
        burst: "PF2E.AreaTypeBurst",
        cone: "PF2E.AreaTypeCone",
        cube: "PF2E.AreaTypeCube",
        emanation: "PF2E.AreaTypeEmanation",
        line: "PF2E.AreaTypeLine",
        square: "PF2E.AreaTypeSquare",
    },

    areaSizes: {
        5: "PF2E.AreaSize5",
        10: "PF2E.AreaSize10",
        15: "PF2E.AreaSize15",
        20: "PF2E.AreaSize20",
        25: "PF2E.AreaSize25",
        30: "PF2E.AreaSize30",
        40: "PF2E.AreaSize40",
        45: "PF2E.AreaSize45",
        50: "PF2E.AreaSize50",
        60: "PF2E.AreaSize60",
        65: "PF2E.AreaSize65",
        75: "PF2E.AreaSize75",
        80: "PF2E.AreaSize80",
        90: "PF2E.AreaSize90",
        100: "PF2E.AreaSize100",
        120: "PF2E.AreaSize120",
        360: "PF2E.AreaSize360",
        500: "PF2E.AreaSize500",
        1000: "PF2E.AreaSize1000",
        1320: "PF2E.AreaSizeQuarterMile",
        5280: "PF2E.AreaSize1Mile",
    },

    alignments,
    alignmentTraits,

    attitude: {
        hostile: "PF2E.Attitudes.Hostile",
        unfriendly: "PF2E.Attitudes.Unfriendly",
        indifferent: "PF2E.Attitudes.Indifferent",
        friendly: "PF2E.Attitudes.Friendly",
        helpful: "PF2E.Attitudes.Helpful",
    },

    skillList: {
        acrobatics: "PF2E.SkillAcrobatics",
        arcana: "PF2E.SkillArcana",
        athletics: "PF2E.SkillAthletics",
        crafting: "PF2E.SkillCrafting",
        deception: "PF2E.SkillDeception",
        diplomacy: "PF2E.SkillDiplomacy",
        intimidation: "PF2E.SkillIntimidation",
        medicine: "PF2E.SkillMedicine",
        nature: "PF2E.SkillNature",
        occultism: "PF2E.SkillOccultism",
        performance: "PF2E.SkillPerformance",
        religion: "PF2E.SkillReligion",
        society: "PF2E.SkillSociety",
        stealth: "PF2E.SkillStealth",
        survival: "PF2E.SkillSurvival",
        thievery: "PF2E.SkillThievery",
        lore: "PF2E.SkillLore",
    },

    spellComponents: {
        V: "PF2E.SpellComponentV",
        S: "PF2E.SpellComponentS",
        M: "PF2E.SpellComponentM",
        F: "PF2E.SpellComponentF",
    },

    spellCategories: {
        spell: "PF2E.SpellCategorySpell",
        focus: "PF2E.SpellCategoryFocus",
        ritual: "PF2E.SpellCategoryRitual",
    },

    spellTypes: {
        attack: "PF2E.SpellTypeAttack",
        save: "PF2E.SpellTypeSave",
        heal: "PF2E.SpellTypeHeal",
        utility: "PF2E.SpellTypeUtility",
    },

    spellLevels: {
        1: "PF2E.SpellLevel1",
        2: "PF2E.SpellLevel2",
        3: "PF2E.SpellLevel3",
        4: "PF2E.SpellLevel4",
        5: "PF2E.SpellLevel5",
        6: "PF2E.SpellLevel6",
        7: "PF2E.SpellLevel7",
        8: "PF2E.SpellLevel8",
        9: "PF2E.SpellLevel9",
        10: "PF2E.SpellLevel10",
    }, // TODO: Compute levels!

    featTypes,

    actionTypes: {
        action: "PF2E.ActionTypeAction",
        reaction: "PF2E.ActionTypeReaction",
        free: "PF2E.ActionTypeFree",
        passive: "PF2E.ActionTypePassive",
    },

    actionsNumber: {
        1: "PF2E.ActionNumber1",
        2: "PF2E.ActionNumber2",
        3: "PF2E.ActionNumber3",
    },

    actionCategories: {
        interaction: "PF2E.ActionCategoryInteraction",
        defensive: "PF2E.ActionCategoryDefensive",
        offensive: "PF2E.ActionCategoryOffensive",
    },

    frequencies: {
        PT1M: "PF2E.Duration.PT1M",
        PT10M: "PF2E.Duration.PT10M",
        PT1H: "PF2E.Duration.PT1H",
        PT24H: "PF2E.Duration.PT24H",
        day: "PF2E.Duration.day",
        P1W: "PF2E.Duration.P1W",
    },

    timeUnits: {
        rounds: "PF2E.Time.Unit.Rounds",
        minutes: "PF2E.Time.Unit.Minutes",
        hours: "PF2E.Time.Unit.Hours",
        days: "PF2E.Time.Unit.Days",
        unlimited: "PF2E.Time.Unit.Unlimited",
        encounter: "PF2E.Time.Unit.UntilEncounterEnds",
    },

    // Proficiency Multipliers
    proficiencyLevels: [
        "PF2E.ProficiencyLevel0", // untrained
        "PF2E.ProficiencyLevel1", // trained
        "PF2E.ProficiencyLevel2", // expert
        "PF2E.ProficiencyLevel3", // master
        "PF2E.ProficiencyLevel4", // legendary
    ] as const,

    actorSizes: sizeTypes,

    actorTypes,

    speedTypes: {
        swim: "PF2E.SpeedTypesSwim",
        climb: "PF2E.SpeedTypesClimb",
        fly: "PF2E.SpeedTypesFly",
        burrow: "PF2E.SpeedTypesBurrow",
    },

    prerequisitePlaceholders: {
        prerequisite1: "PF2E.Prerequisite1",
        prerequisite2: "PF2E.Prerequisite2",
        prerequisite3: "PF2E.Prerequisite3",
        prerequisite4: "PF2E.Prerequisite4",
        prerequisite5: "PF2E.Prerequisite5",
    },

    senses,

    senseAcuity,

    bulkTypes: {
        L: "PF2E.BulkTypeLight",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
        17: "17",
        18: "18",
        19: "19",
        20: "20",
        21: "21",
        22: "22",
        23: "23",
        24: "24",
        25: "25",
        26: "26",
        27: "27",
        28: "28",
        29: "29",
        30: "30",
        31: "31",
        32: "32",
        33: "33",
        34: "34",
        35: "35",
        36: "36",
        37: "37",
        38: "38",
        39: "39",
        40: "40",
        41: "41",
        42: "42",
        43: "43",
        44: "44",
        45: "45",
        46: "46",
        47: "47",
        48: "48",
        49: "49",
        50: "50",
    },

    conditionTypes,

    pfsFactions: {
        EA: "PF2E.PFS.Factions.EA",
        GA: "PF2E.PFS.Factions.GA",
        HH: "PF2E.PFS.Factions.HH",
        VS: "PF2E.PFS.Factions.VS",
        RO: "PF2E.PFS.Factions.RO",
        VW: "PF2E.PFS.Factions.VW",
    },

    pfsSchools: {
        none: "PF2E.PFS.School.None",
        scrolls: "PF2E.PFS.School.Scrolls",
        spells: "PF2E.PFS.School.Spells",
        swords: "PF2E.PFS.School.Swords",
    },

    immunityTypes,

    // Languages, alphabetical by common, uncommon, secret
    languages: {
        common: "PF2E.LanguageCommon",
        draconic: "PF2E.LanguageDraconic",
        dwarven: "PF2E.LanguageDwarven",
        elven: "PF2E.LanguageElven",
        gnomish: "PF2E.LanguageGnomish",
        goblin: "PF2E.LanguageGoblin",
        halfling: "PF2E.LanguageHalfling",
        jotun: "PF2E.LanguageJotun",
        orcish: "PF2E.LanguageOrcish",
        sylvan: "PF2E.LanguageSylvan",
        undercommon: "PF2E.LanguageUndercommon",
        ysoki: "PF2E.LanguageYsoki",
        abyssal: "PF2E.LanguageAbyssal",
        adlet: "PF2E.LanguageAdlet",
        aklo: "PF2E.LanguageAklo",
        akitonian: "PF2E.LanguageAkitonian",
        alghollthu: "PF2E.LanguageAlghollthu",
        amurrun: "PF2E.LanguageAmurrun",
        anadi: "PF2E.LanguageAnadi",
        "ancient-osiriani": "PF2E.LanguageAncientOsiriani",
        anugobu: "PF2E.LanguageAnugobu",
        arcadian: "PF2E.LanguageArcadian",
        aquan: "PF2E.LanguageAquan",
        arboreal: "PF2E.LanguageArboreal",
        auran: "PF2E.LanguageAuran",
        boggard: "PF2E.LanguageBoggard",
        calda: "PF2E.LanguageCalda",
        caligni: "PF2E.LanguageCaligni",
        celestial: "PF2E.LanguageCelestial",
        cyclops: "PF2E.LanguageCyclops",
        daemonic: "PF2E.LanguageDaemonic",
        destrachan: "PF2E.LanguageDestrachan",
        drooni: "PF2E.LanguageDrooni",
        dziriak: "PF2E.LanguageDziriak",
        ekujae: "PF2E.LanguageEkujae",
        erutaki: "PF2E.LanguageErutaki",
        formian: "PF2E.LanguageFormian",
        garundi: "PF2E.LanguageGarundi",
        girtablilu: "PF2E.LanguageGirtablilu",
        gnoll: "PF2E.LanguageGnoll",
        goloma: "PF2E.LanguageGoloma",
        grippli: "PF2E.LanguageGrippli",
        hallit: "PF2E.LanguageHallit",
        hwan: "PF2E.LanguageHwan",
        iblydan: "PF2E.LanguageIblydan",
        ignan: "PF2E.LanguageIgnan",
        ikeshti: "PF2E.LanguageIkeshti",
        immolis: "PF2E.LanguageImmolis",
        infernal: "PF2E.LanguageInfernal",
        iruxi: "PF2E.LanguageIruxi",
        jistkan: "PF2E.LanguageJistkan",
        jyoti: "PF2E.LanguageJyoti",
        kaava: "PF2E.LanguageKaava",
        kashrishi: "PF2E.LanguageKashrishi",
        kibwani: "PF2E.LanguageKibwani",
        kitsune: "PF2E.LanguageKitsune",
        kelish: "PF2E.LanguageKelish",
        lirgeni: "PF2E.LanguageLirgeni",
        mahwek: "PF2E.LanguageMahwek",
        minaten: "PF2E.LanguageMinaten",
        minkaian: "PF2E.LanguageMinkaian",
        mwangi: "PF2E.LanguageMwangi",
        mzunu: "PF2E.LanguageMzunu",
        nagaji: "PF2E.LanguageNagaji",
        necril: "PF2E.LanguageNecril",
        ocotan: "PF2E.LanguageOcotan",
        okaiyan: "PF2E.LanguageOkaiyan",
        osiriani: "PF2E.LanguageOsiriani",
        protean: "PF2E.LanguageProtean",
        rasu: "PF2E.LanguageRasu",
        ratajin: "PF2E.LanguageRatajin",
        razatlani: "PF2E.LanguageRazatlani",
        requian: "PF2E.LanguageRequian",
        russian: "PF2E.LanguageRussian",
        senzar: "PF2E.LanguageSenzar",
        shadowtongue: "PF2E.LanguageShadowtongue",
        shobhad: "PF2E.LanguageShobhad",
        shisk: "PF2E.LanguageShisk",
        shoanti: "PF2E.LanguageShoanti",
        shoony: "PF2E.LanguageShoony",
        skald: "PF2E.LanguageSkald",
        sphinx: "PF2E.LanguageSphinx",
        strix: "PF2E.LanguageStrix",
        taldane: "PF2E.LanguageTaldane",
        tekritanin: "PF2E.LanguageTekritanin",
        tengu: "PF2E.LanguageTengu",
        terran: "PF2E.LanguageTerran",
        thassilonian: "PF2E.LanguageThassilonian",
        tien: "PF2E.LanguageTien",
        utopian: "PF2E.LanguageUtopian",
        vanara: "PF2E.LanguageVanara",
        varisian: "PF2E.LanguageVarisian",
        varki: "PF2E.LanguageVarki",
        vishkanyan: "PF2E.LanguageVishkanyan",
        vudrani: "PF2E.LanguageVudrani",
        wyrwood: "PF2E.LanguageWyrwood",
        xanmba: "PF2E.LanguageXanmba",
        androffan: "PF2E.LanguageAndroffan",
        azlanti: "PF2E.LanguageAzlanti",
        grioth: "PF2E.LanguageGrioth",
        kovintal: "PF2E.LanguageKovintal",
        migo: "PF2E.LanguageMiGo",
        munavri: "PF2E.LanguageMunavri",
        samsaran: "PF2E.LanguageSamsaran",
        sasquatch: "PF2E.LanguageSasquatch",
        shae: "PF2E.LanguageShae",
        yithian: "PF2E.LanguageYithian",
        druidic: "PF2E.LanguageDruidic",
    },

    attackEffects: {
        grab: "PF2E.AttackEffectGrab",
        "improved-grab": "PF2E.AttackEffectImprovedGrab",
        constrict: "PF2E.AttackEffectConstrict",
        "greater-constrict": "PF2E.AttackEffectGreaterConstrict",
        knockdown: "PF2E.AttackEffectKnockdown",
        "improved-knockdown": "PF2E.AttackEffectImprovedKnockdown",
        push: "PF2E.AttackEffectPush",
        "improved-push": "PF2E.AttackEffectImprovedPush",
        trip: "PF2E.AttackEffectTrip",
    },

    // Year offsets relative to the current actual year
    worldClock: {
        AR: { yearOffset: 2700 },
        IC: { yearOffset: 5200 },
        AD: { yearOffset: -95 },
        CE: { yearOffset: 0 },
    },

    runes: {
        weapon: {
            property: { ...WEAPON_PROPERTY_RUNES },
        },
    },

    SETTINGS: {
        automation: {
            rulesBasedVision: {
                name: "PF2E.SETTINGS.Automation.RulesBasedVision.Name",
                hint: "PF2E.SETTINGS.Automation.RulesBasedVision.Hint",
            },
            iwr: {
                name: "PF2E.SETTINGS.Automation.IWR.Name",
                hint: "PF2E.SETTINGS.Automation.IWR.Hint",
            },
            effectExpiration: {
                name: "PF2E.SETTINGS.Automation.EffectExpiration.Name",
                hint: "PF2E.SETTINGS.Automation.EffectExpiration.Hint",
            },
            removeExpiredEffects: {
                name: "PF2E.SETTINGS.Automation.RemoveExpiredEffects.Name",
                hint: "PF2E.SETTINGS.Automation.RemoveExpiredEffects.Hint",
            },
            flankingDetection: {
                name: "PF2E.SETTINGS.Automation.FlankingDetection.Name",
                hint: "PF2E.SETTINGS.Automation.FlankingDetection.Hint",
            },
            actorsDeadAtZero: {
                name: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.Name",
                hint: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.Hint",
                neither: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.Neither",
                npcsOnly: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.NPCsOnly",
                pcsOnly: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.PCsOnly",
                both: "PF2E.SETTINGS.Automation.ActorsDeadAtZero.Both",
            },
            lootableNPCs: {
                name: "PF2E.SETTINGS.Automation.LootableNPCs.Name",
                hint: "PF2E.SETTINGS.Automation.LootableNPCs.Hint",
            },
        },
        homebrew: {
            creatureTraits: {
                name: "PF2E.SETTINGS.Homebrew.CreatureTraits.Name",
                hint: "PF2E.SETTINGS.Homebrew.CreatureTraits.Hint",
            },
            featTraits: {
                name: "PF2E.SETTINGS.Homebrew.FeatTraits.Name",
                hint: "PF2E.SETTINGS.Homebrew.FeatTraits.Hint",
            },
            languages: {
                name: "PF2E.SETTINGS.Homebrew.Languages.Name",
                hint: "PF2E.SETTINGS.Homebrew.Languages.Hint",
            },
            magicSchools: {
                name: "PF2E.SETTINGS.Homebrew.MagicSchools.Name",
                hint: "PF2E.SETTINGS.Homebrew.MagicSchools.Hint",
            },
            spellTraits: {
                name: "PF2E.SETTINGS.Homebrew.SpellTraits.Name",
                hint: "PF2E.SETTINGS.Homebrew.SpellTraits.Hint",
            },
            weaponCategories: {
                name: "PF2E.SETTINGS.Homebrew.WeaponCategories.Name",
                hint: "PF2E.SETTINGS.Homebrew.WeaponCategories.Hint",
            },
            weaponGroups: {
                name: "PF2E.SETTINGS.Homebrew.WeaponGroups.Name",
                hint: "PF2E.SETTINGS.Homebrew.WeaponGroups.Hint",
            },
            baseWeapons: {
                name: "PF2E.SETTINGS.Homebrew.BaseWeapons.Name",
                hint: "PF2E.SETTINGS.Homebrew.BaseWeapons.Hint",
            },
            weaponTraits: {
                name: "PF2E.SETTINGS.Homebrew.WeaponTraits.Name",
                hint: "PF2E.SETTINGS.Homebrew.WeaponTraits.Hint",
            },
            equipmentTraits: {
                name: "PF2E.SETTINGS.Homebrew.EquipmentTraits.Name",
                hint: "PF2E.SETTINGS.Homebrew.EquipmentTraits.Hint",
            },
        },
        worldClock: {
            name: "PF2E.SETTINGS.WorldClock.Name",
            label: "PF2E.SETTINGS.WorldClock.Label",
            hint: "PF2E.SETTINGS.WorldClock.Hint",
            dateTheme: {
                name: "PF2E.SETTINGS.WorldClock.DateTheme.Name",
                hint: "PF2E.SETTINGS.WorldClock.DateTheme.Hint",
                AR: "PF2E.SETTINGS.WorldClock.DateTheme.AR",
                AD: "PF2E.SETTINGS.WorldClock.DateTheme.AD",
                CE: "PF2E.SETTINGS.WorldClock.DateTheme.CE",
            },
            timeConvention: {
                name: "PF2E.SETTINGS.WorldClock.TimeConvention.Name",
                hint: "PF2E.SETTINGS.WorldClock.TimeConvention.Hint",
                twentyFour: "PF2E.SETTINGS.WorldClock.TimeConvention.TwentyFour",
                twelve: "PF2E.SETTINGS.WorldClock.TimeConvention.Twelve",
            },
            showClockButton: {
                name: "PF2E.SETTINGS.WorldClock.ShowClockButton.Name",
                hint: "PF2E.SETTINGS.WorldClock.ShowClockButton.Hint",
            },
            playersCanView: {
                name: "PF2E.SETTINGS.WorldClock.PlayersCanView.Name",
                hint: "PF2E.SETTINGS.WorldClock.PlayersCanView.Hint",
            },
            syncDarkness: {
                name: "PF2E.SETTINGS.WorldClock.SyncDarkness.Name",
                hint: "PF2E.SETTINGS.WorldClock.SyncDarkness.Hint",
            },
            syncDarknessScene: {
                name: "PF2E.SETTINGS.WorldClock.SyncDarknessScene.Name",
                hint: "PF2E.SETTINGS.WorldClock.SyncDarknessScene.Hint",
                enabled: "PF2E.SETTINGS.WorldClock.SyncDarknessScene.Enabled",
                disabled: "PF2E.SETTINGS.WorldClock.SyncDarknessScene.Disabled",
                default: "PF2E.SETTINGS.WorldClock.SyncDarknessScene.Default",
            },
            worldCreatedOn: {
                name: "PF2E.SETTINGS.WorldClock.WorldCreatedOn.Name",
                hint: "PF2E.SETTINGS.WorldClock.WorldCreatedOn.Hint",
            },
        },
        CampaignFeats: {
            name: "PF2E.SETTINGS.CampaignFeats.Name",
            hint: "PF2E.SETTINGS.CampaignFeats.Hint",
        },
    },

    Actor: {
        documentClasses: {
            character: CharacterPF2e,
            npc: NPCPF2e,
            hazard: HazardPF2e,
            loot: LootPF2e,
            familiar: FamiliarPF2e,
            vehicle: VehiclePF2e,
        },
    },

    Item: {
        documentClasses: {
            action: ActionItemPF2e,
            affliction: AfflictionPF2e,
            ancestry: AncestryPF2e,
            armor: ArmorPF2e,
            background: BackgroundPF2e,
            backpack: ContainerPF2e,
            book: BookPF2e,
            class: ClassPF2e,
            condition: ConditionPF2e,
            consumable: ConsumablePF2e,
            deity: DeityPF2e,
            effect: EffectPF2e,
            equipment: EquipmentPF2e,
            feat: FeatPF2e,
            heritage: HeritagePF2e,
            kit: KitPF2e,
            lore: LorePF2e,
            melee: MeleePF2e,
            spell: SpellPF2e,
            spellcastingEntry: SpellcastingEntryPF2e,
            treasure: TreasurePF2e,
            weapon: WeaponPF2e,
        },
        traits: {
            action: actionTraits,
            affliction: actionTraits,
            armor: armorTraits,
            ancestry: creatureTraits,
            backpack: equipmentTraits,
            book: equipmentTraits,
            consumable: consumableTraits,
            equipment: equipmentTraits,
            feat: featTraits,
            heritage: featTraits,
            kit: classTraits,
            melee: npcAttackTraits,
            spell: spellTraits,
            weapon: weaponTraits,
        },
    },

    JournalEntry: { sheetClass: JournalSheetPF2e },

    Canvas: {
        darkness: {
            default: CONFIG.Canvas.darknessColor,
            gmVision: 0x76739e,
        },
    },
};
