import * as R from "remeda";
import { materialDamageEffects } from "./damage.ts";

const materialIWR = R.mapValues(
    // Exclude niche materials from APs that have no IWR properties, as well as ones that count as more-common materials
    R.omit(materialDamageEffects, [
        "keep-stone",
        "peachwood",
        "sisterstone-dusk",
        "sisterstone-scarlet",
        "sovereign-steel",
        "warpglass",
    ]),
    (_v, k) => `PF2E.Damage.IWR.Type.${k}`,
);

const immunityTypes = {
    ...materialIWR,
    acid: "PF2E.Damage.RollFlavor.acid",
    air: "PF2E.Damage.RollFlavor.air",
    "area-damage": "PF2E.Damage.IWR.Type.area-damage",
    auditory: "PF2E.Damage.IWR.Type.auditory",
    bleed: "PF2E.Damage.RollFlavor.bleed",
    blinded: "PF2E.Damage.IWR.Type.blinded",
    bludgeoning: "PF2E.Damage.RollFlavor.bludgeoning",
    chaotic: "PF2E.Damage.RollFlavor.chaotic",
    clumsy: "PF2E.Damage.IWR.Type.clumsy",
    cold: "PF2E.Damage.RollFlavor.cold",
    confused: "PF2E.Damage.IWR.Type.confused",
    conjuration: "PF2E.Damage.IWR.Type.conjuration",
    controlled: "PF2E.Damage.IWR.Type.controlled",
    "critical-hits": "PF2E.Damage.IWR.Type.critical-hits",
    curse: "PF2E.Damage.IWR.Type.curse",
    custom: "", // Label provided by rule element
    darkwood: "PF2E.Damage.IWR.Type.darkwood",
    dazzled: "PF2E.Damage.IWR.Type.dazzled",
    deafened: "PF2E.Damage.IWR.Type.deafened",
    "death-effects": "PF2E.Damage.IWR.Type.death-effects",
    disease: "PF2E.Damage.IWR.Type.disease",
    doomed: "PF2E.Damage.IWR.Type.doomed",
    drained: "PF2E.Damage.IWR.Type.drained",
    earth: "PF2E.Damage.RollFlavor.earth",
    electricity: "PF2E.Damage.RollFlavor.electricity",
    emotion: "PF2E.Damage.IWR.Type.emotion",
    enchantment: "PF2E.Damage.IWR.Type.enchantment",
    energy: "PF2E.Damage.IWR.Type.energy",
    enfeebled: "PF2E.Damage.IWR.Type.enfeebled",
    evil: "PF2E.Damage.RollFlavor.evil",
    evocation: "PF2E.Damage.IWR.Type.evocation",
    fascinated: "PF2E.Damage.IWR.Type.fascinated",
    fatigued: "PF2E.Damage.IWR.Type.fatigued",
    "fear-effects": "PF2E.Damage.IWR.Type.fear-effects",
    fire: "PF2E.Damage.RollFlavor.fire",
    fleeing: "PF2E.Damage.IWR.Type.fleeing",
    force: "PF2E.Damage.RollFlavor.force",
    frightened: "PF2E.Damage.IWR.Type.frightened",
    good: "PF2E.Damage.RollFlavor.good",
    grabbed: "PF2E.Damage.IWR.Type.grabbed",
    healing: "PF2E.Damage.IWR.Type.healing",
    illusion: "PF2E.Damage.IWR.Type.illusion",
    immobilized: "PF2E.Damage.IWR.Type.immobilized",
    inhaled: "PF2E.Damage.IWR.Type.inhaled",
    lawful: "PF2E.Damage.RollFlavor.lawful",
    light: "PF2E.Damage.IWR.Type.light",
    magic: "PF2E.Damage.IWR.Type.magic",
    mental: "PF2E.Damage.RollFlavor.mental",
    metal: "PF2E.Damage.IWR.Type.metal",
    "misfortune-effects": "PF2E.Damage.IWR.Type.misfortune-effects",
    necromancy: "PF2E.Damage.IWR.Type.necromancy",
    "non-magical": "PF2E.Damage.IWR.Type.non-magical",
    "nonlethal-attacks": "PF2E.Damage.IWR.Type.nonlethal-attacks",
    "object-immunities": "PF2E.Damage.IWR.Type.object-immunities",
    "off-guard": "PF2E.Damage.IWR.Type.off-guard",
    olfactory: "PF2E.Damage.IWR.Type.olfactory",
    paralyzed: "PF2E.Damage.IWR.Type.paralyzed",
    "persistent-damage": "PF2E.Damage.IWR.Type.persistent-damage",
    petrified: "PF2E.Damage.IWR.Type.petrified",
    physical: "PF2E.Damage.IWR.Type.physical",
    piercing: "PF2E.Damage.RollFlavor.piercing",
    plant: "PF2E.Damage.IWR.Type.plant",
    poison: "PF2E.Damage.RollFlavor.poison",
    polymorph: "PF2E.Damage.IWR.Type.polymorph",
    possession: "PF2E.Damage.IWR.Type.possession",
    precision: "PF2E.Damage.RollFlavor.precision",
    prone: "PF2E.Damage.IWR.Type.prone",
    radiation: "PF2E.Damage.IWR.Type.radiation",
    restrained: "PF2E.Damage.IWR.Type.restrained",
    "salt-water": "PF2E.Damage.IWR.Type.salt-water",
    scrying: "PF2E.Damage.IWR.Type.scrying",
    sickened: "PF2E.Damage.IWR.Type.sickened",
    slashing: "PF2E.Damage.RollFlavor.slashing",
    sleep: "PF2E.Damage.IWR.Type.sleep",
    slowed: "PF2E.Damage.IWR.Type.slowed",
    sonic: "PF2E.Damage.RollFlavor.sonic",
    "spell-deflection": "PF2E.Damage.IWR.Type.spell-deflection",
    spirit: "PF2E.Damage.RollFlavor.spirit",
    stunned: "PF2E.Damage.IWR.Type.stunned",
    stupefied: "PF2E.Damage.IWR.Type.stupefied",
    "swarm-attacks": "PF2E.Damage.IWR.Type.swarm-attacks",
    "swarm-mind": "PF2E.Damage.IWR.Type.swarm-mind",
    transmutation: "PF2E.Damage.IWR.Type.transmutation",
    trip: "PF2E.Damage.IWR.Type.trip",
    "unarmed-attacks": "PF2E.Damage.IWR.Type.unarmed-attacks",
    unconscious: "PF2E.Damage.IWR.Type.unconscious",
    visual: "PF2E.Damage.IWR.Type.visual",
    vitality: "PF2E.Damage.RollFlavor.vitality",
    void: "PF2E.Damage.RollFlavor.void",
    water: "PF2E.Damage.IWR.Type.water",
    wood: "PF2E.Damage.IWR.Type.wood",
    wounded: "PF2E.Damage.IWR.Type.wounded",
};

const weaknessTypes = {
    ...materialIWR,
    acid: "PF2E.Damage.RollFlavor.acid",
    air: "PF2E.Damage.RollFlavor.air",
    "area-damage": "PF2E.Damage.IWR.Type.area-damage",
    "arrow-vulnerability": "PF2E.Damage.IWR.Type.arrow-vulnerability",
    "axe-vulnerability": "PF2E.Damage.IWR.Type.axe-vulnerability",
    bleed: "PF2E.Damage.RollFlavor.bleed",
    bludgeoning: "PF2E.Damage.RollFlavor.bludgeoning",
    chaotic: "PF2E.Damage.RollFlavor.chaotic",
    cold: "PF2E.Damage.RollFlavor.cold",
    "critical-hits": "PF2E.Damage.IWR.Type.critical-hits",
    custom: "", // Label provided by rule element
    earth: "PF2E.Damage.RollFlavor.earth",
    electricity: "PF2E.Damage.RollFlavor.electricity",
    emotion: "PF2E.Damage.IWR.Type.emotion",
    energy: "PF2E.Damage.IWR.Type.energy",
    evil: "PF2E.Damage.RollFlavor.evil",
    fire: "PF2E.Damage.RollFlavor.fire",
    force: "PF2E.Damage.RollFlavor.force",
    "ghost-touch": "PF2E.Damage.IWR.Type.ghost-touch",
    glass: "PF2E.Damage.IWR.Type.glass",
    good: "PF2E.Damage.RollFlavor.good",
    lawful: "PF2E.Damage.RollFlavor.lawful",
    light: "PF2E.Damage.IWR.Type.light",
    magical: "PF2E.Damage.IWR.Type.magical",
    mental: "PF2E.Damage.RollFlavor.mental",
    metal: "PF2E.Damage.RollFlavor.metal",
    "non-magical": "PF2E.Damage.IWR.Type.non-magical",
    "nonlethal-attacks": "PF2E.Damage.IWR.Type.nonlethal-attacks",
    physical: "PF2E.Damage.IWR.Type.physical",
    piercing: "PF2E.Damage.RollFlavor.piercing",
    plant: "PF2E.Damage.IWR.Type.plant",
    poison: "PF2E.Damage.RollFlavor.poison",
    precision: "PF2E.Damage.RollFlavor.precision",
    radiation: "PF2E.Damage.IWR.Type.radiation",
    salt: "PF2E.Damage.IWR.Type.salt",
    "salt-water": "PF2E.Damage.IWR.Type.salt-water",
    slashing: "PF2E.Damage.RollFlavor.slashing",
    sonic: "PF2E.Damage.RollFlavor.sonic",
    spells: "PF2E.Damage.IWR.Type.spells",
    spirit: "PF2E.Damage.RollFlavor.spirit",
    "splash-damage": "PF2E.Damage.IWR.Type.splash-damage",
    "unarmed-attacks": "PF2E.Damage.IWR.Type.unarmed-attacks",
    "vampire-weaknesses": "PF2E.Damage.IWR.Type.vampire-weaknesses",
    vitality: "PF2E.Damage.RollFlavor.vitality",
    void: "PF2E.Damage.RollFlavor.void",
    vorpal: "PF2E.Damage.IWR.Type.vorpal",
    "vorpal-fear": "PF2E.Damage.IWR.Type.vorpal-fear",
    "vulnerable-to-sunlight": "PF2E.Damage.IWR.Type.vulnerable-to-sunlight",
    water: "PF2E.Damage.IWR.Type.water",
    weapons: "PF2E.Damage.IWR.Type.weapons",
    "weapons-shedding-bright-light": "PF2E.Damage.IWR.Type.weapons-shedding-bright-light",
    wood: "PF2E.Damage.IWR.Type.wood",
};

const resistanceTypes = {
    ...materialIWR,
    acid: "PF2E.Damage.RollFlavor.acid",
    air: "PF2E.Damage.RollFlavor.air",
    "all-damage": "PF2E.Damage.IWR.Type.all-damage",
    "area-damage": "PF2E.Damage.IWR.Type.area-damage",
    bleed: "PF2E.Damage.RollFlavor.bleed",
    bludgeoning: "PF2E.Damage.RollFlavor.bludgeoning",
    chaotic: "PF2E.Damage.RollFlavor.chaotic",
    cold: "PF2E.Damage.RollFlavor.cold",
    "critical-hits": "PF2E.Damage.IWR.Type.critical-hits",
    custom: "", // Label provided by rule element
    "damage-from-spells": "PF2E.Damage.IWR.Type.damage-from-spells",
    earth: "PF2E.Damage.RollFlavor.earth",
    electricity: "PF2E.Damage.RollFlavor.electricity",
    energy: "PF2E.Damage.IWR.Type.energy",
    evil: "PF2E.Damage.RollFlavor.evil",
    fire: "PF2E.Damage.RollFlavor.fire",
    force: "PF2E.Damage.RollFlavor.force",
    "ghost-touch": "PF2E.Damage.IWR.Type.ghost-touch",
    good: "PF2E.Damage.RollFlavor.good",
    lawful: "PF2E.Damage.RollFlavor.lawful",
    light: "PF2E.Damage.IWR.Type.light",
    magical: "PF2E.Damage.IWR.Type.magical",
    mental: "PF2E.Damage.RollFlavor.mental",
    metal: "PF2E.Damage.RollFlavor.metal",
    "non-magical": "PF2E.Damage.IWR.Type.non-magical",
    nonlethal: "PF2E.Damage.IWR.Type.nonlethal",
    "nonlethal-attacks": "PF2E.Damage.IWR.Type.nonlethal-attacks",
    physical: "PF2E.Damage.IWR.Type.physical",
    piercing: "PF2E.Damage.RollFlavor.piercing",
    plant: "PF2E.Damage.IWR.Type.plant",
    poison: "PF2E.Damage.RollFlavor.poison",
    precision: "PF2E.Damage.RollFlavor.precision",
    "protean-anatomy": "PF2E.Damage.IWR.Type.protean-anatomy",
    radiation: "PF2E.Damage.IWR.Type.radiation",
    salt: "PF2E.Damage.IWR.Type.salt",
    "salt-water": "PF2E.Damage.IWR.Type.salt-water",
    slashing: "PF2E.Damage.RollFlavor.slashing",
    sonic: "PF2E.Damage.RollFlavor.sonic",
    spells: "PF2E.Damage.IWR.Type.spells",
    spirit: "PF2E.Damage.RollFlavor.spirit",
    "unarmed-attacks": "PF2E.Damage.IWR.Type.unarmed-attacks",
    vitality: "PF2E.Damage.RollFlavor.vitality",
    void: "PF2E.Damage.RollFlavor.void",
    vorpal: "PF2E.Damage.IWR.Type.vorpal",
    "vorpal-adamantine": "PF2E.Damage.IWR.Type.vorpal-adamantine",
    water: "PF2E.Damage.IWR.Type.water",
    weapons: "PF2E.Damage.IWR.Type.weapons",
    "weapons-shedding-bright-light": "PF2E.Damage.IWR.Type.weapons-shedding-bright-light",
    wood: "PF2E.Damage.IWR.Type.wood",
};

export { immunityTypes, resistanceTypes, weaknessTypes };
