import { OtherArmorTag } from "@item/armor/types.ts";
import { BackgroundTrait } from "@item/background/types.ts";
import { ClassTrait } from "@item/class/types.ts";
import { OtherConsumableTag } from "@item/consumable/types.ts";
import { PreciousMaterialType } from "@item/physical/types.ts";
import { MagicTradition } from "@item/spell/types.ts";
import { OtherWeaponTag } from "@item/weapon/types.ts";
import * as R from "remeda";

// Ancestry and heritage traits
const ancestryTraits = {
    aiuvarin: "PF2E.TraitAiuvarin",
    anadi: "PF2E.TraitAnadi",
    android: "PF2E.TraitAndroid",
    aphorite: "PF2E.TraitAphorite",
    ardande: "PF2E.TraitArdande",
    athamaru: "PF2E.TraitAthamaru",
    automaton: "PF2E.TraitAutomaton",
    "awakened-animal": "PF2E.TraitAwakenedAnimal",
    azarketi: "PF2E.TraitAzarketi",
    beastkin: "PF2E.TraitBeastkin",
    bugbear: "PF2E.TraitBugbear",
    catfolk: "PF2E.TraitCatfolk",
    centaur: "PF2E.TraitCentaur",
    changeling: "PF2E.TraitChangeling",
    conrasu: "PF2E.TraitConrasu",
    dhampir: "PF2E.TraitDhampir",
    dragonblood: "PF2E.TraitDragonblood",
    dragonet: "PF2E.TraitDragonet",
    dromaar: "PF2E.TraitDromaar",
    duskwalker: "PF2E.TraitDuskwalker",
    dwarf: "PF2E.TraitDwarf",
    elf: "PF2E.TraitElf",
    fetchling: "PF2E.TraitFetchling",
    fleshwarp: "PF2E.TraitFleshwarp",
    ganzi: "PF2E.TraitGanzi",
    geniekin: "PF2E.TraitGeniekin",
    ghoran: "PF2E.TraitGhoran",
    gnoll: "PF2E.TraitGnoll",
    gnome: "PF2E.TraitGnome",
    goblin: "PF2E.TraitGoblin",
    goloma: "PF2E.TraitGoloma",
    grippli: "PF2E.TraitGrippli",
    halfling: "PF2E.TraitHalfling",
    hobgoblin: "PF2E.TraitHobgoblin",
    human: "PF2E.TraitHuman",
    hungerseed: "PF2E.TraitHungerseed",
    jotunborn: "PF2E.TraitJotunborn",
    kashrishi: "PF2E.TraitKashrishi",
    kitsune: "PF2E.TraitKitsune",
    kobold: "PF2E.TraitKobold",
    leshy: "PF2E.TraitLeshy",
    lizardfolk: "PF2E.TraitLizardfolk",
    merfolk: "PF2E.TraitMerfolk",
    minotaur: "PF2E.TraitMinotaur",
    nagaji: "PF2E.TraitNagaji",
    naari: "PF2E.TraitNaari",
    nephilim: "PF2E.TraitNephilim",
    orc: "PF2E.TraitOrc",
    oread: "PF2E.TraitOread",
    poppet: "PF2E.TraitPoppet",
    ratfolk: "PF2E.TraitRatfolk",
    reflection: "PF2E.TraitReflection",
    samsaran: "PF2E.TraitSamsaran",
    sarangay: "PF2E.TraitSarangay",
    shisk: "PF2E.TraitShisk",
    shoony: "PF2E.TraitShoony",
    skeleton: "PF2E.TraitSkeleton",
    sprite: "PF2E.TraitSprite",
    strix: "PF2E.TraitStrix",
    suli: "PF2E.TraitSuli",
    surki: "PF2E.TraitSurki",
    sylph: "PF2E.TraitSylph",
    tanuki: "PF2E.TraitTanuki",
    talos: "PF2E.TraitTalos",
    tengu: "PF2E.TraitTengu",
    undine: "PF2E.TraitUndine",
    vanara: "PF2E.TraitVanara",
    vishkanya: "PF2E.TraitVishkanya",
    wayang: "PF2E.TraitWayang",
    yaksha: "PF2E.TraitYaksha",
    yaoguai: "PF2E.TraitYaoguai",
};

const elementTraits = {
    air: "PF2E.TraitAir",
    earth: "PF2E.TraitEarth",
    fire: "PF2E.TraitFire",
    metal: "PF2E.TraitMetal",
    water: "PF2E.TraitWater",
    wood: "PF2E.TraitWood",
};
type ElementTrait = keyof typeof elementTraits;

const energyDamageTypes = {
    acid: "PF2E.TraitAcid",
    cold: "PF2E.TraitCold",
    electricity: "PF2E.TraitElectricity",
    fire: "PF2E.TraitFire",
    force: "PF2E.TraitForce",
    sonic: "PF2E.TraitSonic",
    vitality: "PF2E.TraitVitality",
    void: "PF2E.TraitVoid",
};

const magicTraditions: Record<MagicTradition, string> = {
    arcane: "PF2E.TraitArcane",
    divine: "PF2E.TraitDivine",
    occult: "PF2E.TraitOccult",
    primal: "PF2E.TraitPrimal",
};

const sanctificationTraits = {
    holy: "PF2E.TraitHoly",
    unholy: "PF2E.TraitUnholy",
};

const creatureTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    aberration: "PF2E.TraitAberration",
    aeon: "PF2E.TraitAeon",
    aesir: "PF2E.TraitAesir",
    agathion: "PF2E.TraitAgathion",
    alchemical: "PF2E.TraitAlchemical",
    amphibious: "PF2E.TraitAmphibious",
    angel: "PF2E.TraitAngel",
    animal: "PF2E.TraitAnimal",
    anugobu: "PF2E.TraitAnugobu",
    aquatic: "PF2E.TraitAquatic",
    archon: "PF2E.TraitArchon",
    astral: "PF2E.TraitAstral",
    asura: "PF2E.TraitAsura",
    azata: "PF2E.TraitAzata",
    beast: "PF2E.TraitBeast",
    blight: "PF2E.TraitBlight",
    boggard: "PF2E.TraitBoggard",
    bugbear: "PF2E.TraitBugbear",
    caligni: "PF2E.TraitCaligni",
    celestial: "PF2E.TraitCelestial",
    centaur: "PF2E.TraitCentaur",
    "charau-ka": "PF2E.TraitCharauKa",
    clockwork: "PF2E.TraitClockwork",
    construct: "PF2E.TraitConstruct",
    couatl: "PF2E.TraitCouatl",
    daemon: "PF2E.TraitDaemon",
    darvakka: "PF2E.TraitDarvakka",
    demon: "PF2E.TraitDemon",
    dero: "PF2E.TraitDero",
    devil: "PF2E.TraitDevil",
    dinosaur: "PF2E.TraitDinosaur",
    div: "PF2E.TraitDiv",
    dragon: "PF2E.TraitDragon",
    dream: "PF2E.TraitDream",
    drow: "PF2E.TraitDrow",
    duergar: "PF2E.TraitDuergar",
    eidolon: "PF2E.TraitEidolon",
    elemental: "PF2E.TraitElemental",
    ethereal: "PF2E.TraitEthereal",
    experiment: "PF2E.TraitExperiment",
    fey: "PF2E.TraitFey",
    fiend: "PF2E.TraitFiend",
    formian: "PF2E.TraitFormian",
    fungus: "PF2E.TraitFungus",
    genie: "PF2E.TraitGenie",
    ghoran: "PF2E.TraitGhoran",
    ghost: "PF2E.TraitGhost",
    ghoul: "PF2E.TraitGhoul",
    ghul: "PF2E.TraitGhul",
    giant: "PF2E.TraitGiant",
    gigas: "PF2E.TraitGigas",
    girtablilu: "PF2E.TraitGirtablilu",
    golem: "PF2E.TraitGolem",
    graveknight: "PF2E.TraitGraveknight",
    gremlin: "PF2E.TraitGremlin",
    grioth: "PF2E.TraitGrioth",
    hag: "PF2E.TraitHag",
    hantu: "PF2E.TraitHantu",
    herald: "PF2E.TraitHerald",
    hryngar: "PF2E.TraitHryngar",
    humanoid: "PF2E.TraitHumanoid",
    ikeshti: "PF2E.TraitIkeshti",
    illusion: "PF2E.TraitIllusion",
    incorporeal: "PF2E.TraitIncorporeal",
    inevitable: "PF2E.TraitInevitable",
    kami: "PF2E.TraitKami",
    kaiju: "PF2E.TraitKaiju",
    kovintus: "PF2E.TraitKovintus",
    light: "PF2E.TraitLight",
    lilu: "PF2E.TraitLilu",
    locathah: "PF2E.TraitLocathah",
    maftet: "PF2E.TraitMaftet",
    mental: "PF2E.TraitMental",
    merfolk: "PF2E.TraitMerfolk",
    mindless: "PF2E.TraitMindless",
    minion: "PF2E.TraitMinion",
    monitor: "PF2E.TraitMonitor",
    morlock: "PF2E.TraitMorlock",
    mortic: "PF2E.TraitMortic",
    mummy: "PF2E.TraitMummy",
    munavri: "PF2E.TraitMunavri",
    mutant: "PF2E.TraitMutant",
    mythic: "PF2E.TraitMythic",
    nindoru: "PF2E.TraitNindoru",
    nymph: "PF2E.TraitNymph",
    oni: "PF2E.TraitOni",
    ooze: "PF2E.TraitOoze",
    oread: "PF2E.TraitOread",
    paaridar: "PF2E.TraitPaaridar",
    palinthanos: "PF2E.TraitPalinthanos",
    "persona-flirt": "PF2E.TraitPersonaFlirt",
    "persona-guardian": "PF2E.TraitPersonaGuardian",
    "persona-leader": "PF2E.TraitPersonaLeader",
    "persona-scholar": "PF2E.TraitPersonaScholar",
    "persona-scoundrel": "PF2E.TraitPersonaScoundrel",
    "persona-underdog": "PF2E.TraitPersonaUnderdog",
    "persona-warrior": "PF2E.TraitPersonaWarrior",
    "persona-wildcard": "PF2E.TraitPersonaWildcard",
    petitioner: "PF2E.TraitPetitioner",
    phantom: "PF2E.TraitPhantom",
    plant: "PF2E.TraitPlant",
    poison: "PF2E.TraitPoison",
    protean: "PF2E.TraitProtean",
    psychopomp: "PF2E.TraitPsychopomp",
    qlippoth: "PF2E.TraitQlippoth",
    rakshasa: "PF2E.TraitRakshasa",
    reflection: "PF2E.TraitReflection",
    sahkil: "PF2E.TraitSahkil",
    "sea-devil": "PF2E.TraitSeaDevil",
    sedacthy: "PF2E.TraitSedacthy",
    serpentfolk: "PF2E.TraitSerpentfolk",
    seugathi: "PF2E.TraitSeugathi",
    shabti: "PF2E.TraitShabti",
    shade: "PF2E.TraitShade",
    shadow: "PF2E.TraitShadow",
    shobhad: "PF2E.TraitShobhad",
    siktempora: "PF2E.TraitSiktempora",
    skelm: "PF2E.TraitSkelm",
    skulk: "PF2E.TraitSkulk",
    soulbound: "PF2E.TraitSoulbound",
    spirit: "PF2E.TraitSpirit",
    sporeborn: "PF2E.TraitSporeborn",
    spriggan: "PF2E.TraitSpriggan",
    stheno: "PF2E.TraitStheno",
    summoned: "PF2E.TraitSummoned",
    swarm: "PF2E.TraitSwarm",
    tane: "PF2E.TraitTane",
    tanggal: "PF2E.TraitTanggal",
    time: "PF2E.TraitTime",
    titan: "PF2E.TraitTitan",
    troll: "PF2E.TraitTroll",
    troop: "PF2E.TraitTroop",
    undead: "PF2E.TraitUndead",
    urdefhan: "PF2E.TraitUrdefhan",
    vampire: "PF2E.TraitVampire",
    vanara: "PF2E.TraitVanara",
    velstrac: "PF2E.TraitVelstrac",
    wayang: "PF2E.TraitWayang",
    werecreature: "PF2E.TraitWerecreature",
    wight: "PF2E.TraitWight",
    "wild-hunt": "PF2E.TraitWildHunt",
    wraith: "PF2E.TraitWraith",
    wraithvine: "PF2E.TraitWraithvine",
    wyrwood: "PF2E.TraitWyrwood",
    xulgath: "PF2E.TraitXulgath",
    zombie: "PF2E.TraitZombie",
};

const backgroundTraits: Record<BackgroundTrait, string> = {
    "persona-flirt": "PF2E.TraitPersonaFlirt",
    "persona-guardian": "PF2E.TraitPersonaGuardian",
    "persona-leader": "PF2E.TraitPersonaLeader",
    "persona-scholar": "PF2E.TraitPersonaScholar",
    "persona-scoundrel": "PF2E.TraitPersonaScoundrel",
    "persona-underdog": "PF2E.TraitPersonaUnderdog",
    "persona-warrior": "PF2E.TraitPersonaWarrior",
    "persona-wildcard": "PF2E.TraitPersonaWildcard",
    "pervasive-magic": "PF2E.TraitPervasiveMagic",
};

const classTraits: Record<ClassTrait, string> = {
    alchemist: "PF2E.TraitAlchemist",
    animist: "PF2E.TraitAnimist",
    barbarian: "PF2E.TraitBarbarian",
    bard: "PF2E.TraitBard",
    champion: "PF2E.TraitChampion",
    cleric: "PF2E.TraitCleric",
    commander: "PF2E.TraitCommander",
    druid: "PF2E.TraitDruid",
    exemplar: "PF2E.TraitExemplar",
    fighter: "PF2E.TraitFighter",
    guardian: "PF2E.TraitGuardian",
    gunslinger: "PF2E.TraitGunslinger",
    inventor: "PF2E.TraitInventor",
    investigator: "PF2E.TraitInvestigator",
    kineticist: "PF2E.TraitKineticist",
    magus: "PF2E.TraitMagus",
    monk: "PF2E.TraitMonk",
    oracle: "PF2E.TraitOracle",
    psychic: "PF2E.TraitPsychic",
    ranger: "PF2E.TraitRanger",
    rogue: "PF2E.TraitRogue",
    sorcerer: "PF2E.TraitSorcerer",
    summoner: "PF2E.TraitSummoner",
    swashbuckler: "PF2E.TraitSwashbuckler",
    thaumaturge: "PF2E.TraitThaumaturge",
    witch: "PF2E.TraitWitch",
    wizard: "PF2E.TraitWizard",
};

const damageTraits = {
    ...elementTraits,
    ...energyDamageTypes,
    ...sanctificationTraits,
    light: "PF2E.TraitLight",
    magical: "PF2E.TraitMagical",
    mental: "PF2E.TraitMental",
    nonlethal: "PF2E.TraitNonlethal",
    plant: "PF2E.TraitPlant",
    radiation: "PF2E.TraitRadiation",
    spirit: "PF2E.TraitSpirit",
    vitality: "PF2E.TraitVitality",
    void: "PF2E.TraitVoid",
};

const spellTraits = {
    ...classTraits,
    ...damageTraits,
    ...elementTraits,
    ...magicTraditions,
    ...sanctificationTraits,
    amp: "PF2E.TraitAmp",
    attack: "PF2E.TraitAttack",
    auditory: "PF2E.TraitAuditory",
    aura: "PF2E.TraitAura",
    beast: "PF2E.TraitBeast",
    cantrip: "PF2E.TraitCantrip",
    composition: "PF2E.TraitComposition",
    concentrate: "PF2E.TraitConcentrate",
    consecration: "PF2E.TraitConsecration",
    contingency: "PF2E.TraitContingency",
    curse: "PF2E.TraitCurse",
    cursebound: "PF2E.TraitCursebound",
    darkness: "PF2E.TraitDarkness",
    death: "PF2E.TraitDeath",
    detection: "PF2E.TraitDetection",
    disease: "PF2E.TraitDisease",
    dream: "PF2E.TraitDream",
    eidolon: "PF2E.TraitEidolon",
    emotion: "PF2E.TraitEmotion",
    exploration: "PF2E.TraitExploration",
    extradimensional: "PF2E.TraitExtradimensional",
    fear: "PF2E.TraitFear",
    focus: "PF2E.TraitFocus",
    fortune: "PF2E.TraitFortune",
    fungus: "PF2E.TraitFungus",
    healing: "PF2E.TraitHealing",
    hex: "PF2E.TraitHex",
    illusion: "PF2E.TraitIllusion",
    incapacitation: "PF2E.TraitIncapacitation",
    incarnate: "PF2E.TraitIncarnate",
    incorporeal: "PF2E.TraitIncorporeal",
    inhaled: "PF2E.TraitInhaled",
    light: "PF2E.TraitLight",
    linguistic: "PF2E.TraitLinguistic",
    litany: "PF2E.TraitLitany",
    manipulate: "PF2E.TraitManipulate",
    misfortune: "PF2E.TraitMisfortune",
    morph: "PF2E.TraitMorph",
    move: "PF2E.TraitMove",
    mythic: "PF2E.TraitMythic",
    nonlethal: "PF2E.TraitNonlethal",
    olfactory: "PF2E.TraitOlfactory",
    plant: "PF2E.TraitPlant",
    poison: "PF2E.TraitPoison",
    polymorph: "PF2E.TraitPolymorph",
    possession: "PF2E.TraitPossession",
    prediction: "PF2E.TraitPrediction",
    psyche: "PF2E.TraitPsyche",
    rage: "PF2E.TraitRage",
    revelation: "PF2E.TraitRevelation",
    sanctified: "PF2E.TraitSanctified",
    scrying: "PF2E.TraitScrying",
    shadow: "PF2E.TraitShadow",
    sleep: "PF2E.TraitSleep",
    spellshape: "PF2E.TraitSpellshape",
    stance: "PF2E.TraitStance",
    structure: "PF2E.TraitStructure",
    subtle: "PF2E.TraitSubtle",
    summon: "PF2E.TraitSummon",
    summoned: "PF2E.TraitSummoned",
    teleportation: "PF2E.TraitTeleportation",
    trial: "PF2E.TraitTrial",
    "true-name": "PF2E.TraitTrueName",
    visual: "PF2E.TraitVisual",
};

const weaponTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    adjusted: "PF2E.TraitAdjusted",
    agile: "PF2E.TraitAgile",
    alchemical: "PF2E.TraitAlchemical",
    analog: "PF2E.TraitAnalog",
    apex: "PF2E.TraitApex",
    artifact: "PF2E.TraitArtifact",
    attached: "PF2E.TraitAttached",
    "attached-to-shield": "PF2E.TraitAttachedToShield",
    "attached-to-crossbow-or-firearm": "PF2E.TraitAttachedToCrossbowOrFirearm",
    auditory: "PF2E.TraitAuditory",
    automatic: "PF2E.TraitAutomatic",
    backstabber: "PF2E.TraitBackstabber",
    backswing: "PF2E.TraitBackswing",
    bomb: "PF2E.TraitBomb",
    brace: "PF2E.TraitBrace",
    brutal: "PF2E.TraitBrutal",
    "capacity-2": "PF2E.TraitCapacity2",
    "capacity-3": "PF2E.TraitCapacity3",
    "capacity-4": "PF2E.TraitCapacity4",
    "capacity-5": "PF2E.TraitCapacity5",
    climbing: "PF2E.TraitClimbing",
    clockwork: "PF2E.TraitClockwork",
    cobbled: "PF2E.TraitCobbled",
    combination: "PF2E.TraitCombination",
    concealable: "PF2E.TraitConcealable",
    concussive: "PF2E.TraitConcussive",
    consumable: "PF2E.TraitConsumable",
    "critical-fusion": "PF2E.TraitCriticalFusion",
    cursed: "PF2E.TraitCursed",
    "deadly-d4": "PF2E.TraitDeadlyD4",
    "deadly-d6": "PF2E.TraitDeadlyD6",
    "deadly-d8": "PF2E.TraitDeadlyD8",
    "deadly-d10": "PF2E.TraitDeadlyD10",
    "deadly-d12": "PF2E.TraitDeadlyD12",
    death: "PF2E.TraitDeath",
    disarm: "PF2E.TraitDisarm",
    disease: "PF2E.TraitDisease",
    "double-barrel": "PF2E.TraitDoubleBarrel",
    emotion: "PF2E.TraitEmotion",
    extradimensional: "PF2E.TraitExtradimensional",
    "fatal-aim-d10": "PF2E.TraitFatalAimD10",
    "fatal-aim-d12": "PF2E.TraitFatalAimD12",
    "fatal-d8": "PF2E.TraitFatalD8",
    "fatal-d10": "PF2E.TraitFatalD10",
    "fatal-d12": "PF2E.TraitFatalD12",
    fear: "PF2E.TraitFear",
    finesse: "PF2E.TraitFinesse",
    forceful: "PF2E.TraitForceful",
    fortune: "PF2E.TraitFortune",
    "free-hand": "PF2E.TraitFreeHand",
    fungus: "PF2E.TraitFungus",
    grapple: "PF2E.TraitGrapple",
    hampering: "PF2E.TraitHampering",
    healing: "PF2E.TraitHealing",
    illusion: "PF2E.TraitIllusion",
    infused: "PF2E.TraitInfused",
    inhaled: "PF2E.TraitInhaled",
    injection: "PF2E.TraitInjection",
    intelligent: "PF2E.TraitIntelligent",
    invested: "PF2E.TraitInvested",
    "jousting-d4": "PF2E.TraitJoustingD4",
    "jousting-d6": "PF2E.TraitJoustingD6",
    "jousting-d8": "PF2E.TraitJoustingD8",
    "jousting-d10": "PF2E.TraitJoustingD10",
    kickback: "PF2E.TraitKickback",
    light: "PF2E.TraitLight",
    magical: "PF2E.TraitMagical",
    mental: "PF2E.TraitMental",
    modular: "PF2E.TraitModular",
    monk: "PF2E.TraitMonk",
    mythic: "PF2E.TraitMythic",
    nonlethal: "PF2E.TraitNonlethal",
    olfactory: "PF2E.TraitOlfactory",
    parry: "PF2E.TraitParry",
    plant: "PF2E.TraitPlant",
    poison: "PF2E.TraitPoison",
    propulsive: "PF2E.TraitPropulsive",
    "ranged-trip": "PF2E.TraitRangedTrip",
    razing: "PF2E.TraitRazing",
    reach: "PF2E.TraitReach",
    recovery: "PF2E.TraitRecovery",
    relic: "PF2E.TraitRelic",
    repeating: "PF2E.TraitRepeating",
    resonant: "PF2E.TraitResonant",
    saggorak: "PF2E.TraitSaggorak",
    "scatter-5": "PF2E.TraitScatter5",
    "scatter-10": "PF2E.TraitScatter10",
    "scatter-15": "PF2E.TraitScatter15",
    "scatter-20": "PF2E.TraitScatter20",
    scrying: "PF2E.TraitScrying",
    shadow: "PF2E.TraitShadow",
    shove: "PF2E.TraitShove",
    spirit: "PF2E.TraitSpirit",
    splash: "PF2E.TraitSplash",
    staff: "PF2E.TraitStaff",
    sweep: "PF2E.TraitSweep",
    tearing: "PF2E.TraitTearing",
    tech: "PF2E.TraitTech",
    teleportation: "PF2E.TraitTeleportation",
    tethered: "PF2E.TraitTethered",
    thrown: "PF2E.TraitThrown",
    "thrown-10": "PF2E.TraitThrown10",
    "thrown-15": "PF2E.TraitThrown15",
    "thrown-20": "PF2E.TraitThrown20",
    "thrown-30": "PF2E.TraitThrown30",
    "thrown-40": "PF2E.TraitThrown40",
    "thrown-50": "PF2E.TraitThrown50",
    "thrown-60": "PF2E.TraitThrown60",
    "thrown-80": "PF2E.TraitThrown80",
    "thrown-100": "PF2E.TraitThrown100",
    "thrown-200": "PF2E.TraitThrown200",
    time: "PF2E.TraitTime",
    training: "PF2E.TraitTraining",
    "tracking-1": "PF2E.TraitTracking1",
    "tracking-2": "PF2E.TraitTracking2",
    "tracking-3": "PF2E.TraitTracking3",
    trip: "PF2E.TraitTrip",
    twin: "PF2E.TraitTwin",
    "two-hand-d6": "PF2E.TraitTwoHandD6",
    "two-hand-d8": "PF2E.TraitTwoHandD8",
    "two-hand-d10": "PF2E.TraitTwoHandD10",
    "two-hand-d12": "PF2E.TraitTwoHandD12",
    unarmed: "PF2E.TraitUnarmed",
    vehicular: "PF2E.TraitVehicular",
    venomous: "PF2E.TraitVenomous",
    "versatile-acid": "PF2E.TraitVersatileAcid",
    "versatile-b": "PF2E.TraitVersatileB",
    "versatile-cold": "PF2E.TraitVersatileCold",
    "versatile-electricity": "PF2E.TraitVersatileElectricity",
    "versatile-fire": "PF2E.TraitVersatileFire",
    "versatile-force": "PF2E.TraitVersatileForce",
    "versatile-mental": "PF2E.TraitVersatileMental",
    "versatile-p": "PF2E.TraitVersatileP",
    "versatile-poison": "PF2E.TraitVersatilePoison",
    "versatile-s": "PF2E.TraitVersatileS",
    "versatile-sonic": "PF2E.TraitVersatileSonic",
    "versatile-spirit": "PF2E.TraitVersatileSpirit",
    "versatile-vitality": "PF2E.TraitVersatileVitality",
    "versatile-void": "PF2E.TraitVersatileVoid",
    visual: "PF2E.TraitVisual",
    "volley-20": "PF2E.TraitVolley20",
    "volley-30": "PF2E.TraitVolley30",
    "volley-50": "PF2E.TraitVolley50",
    "volley-60": "PF2E.TraitVolley60",
    wand: "PF2E.TraitWand",
};

const preciousMaterials: Record<PreciousMaterialType, string> = {
    abysium: "PF2E.PreciousMaterialAbysium",
    adamantine: "PF2E.PreciousMaterialAdamantine",
    "cold-iron": "PF2E.PreciousMaterialColdIron",
    dawnsilver: "PF2E.PreciousMaterialDawnsilver",
    duskwood: "PF2E.PreciousMaterialDuskwood",
    djezet: "PF2E.PreciousMaterialDjezet",
    dragonhide: "PF2E.PreciousMaterialDragonhide",
    dreamweb: "PF2E.PreciousMaterialDreamweb",
    "grisantian-pelt": "PF2E.PreciousMaterialGrisantianPelt",
    inubrix: "PF2E.PreciousMaterialInubrix",
    "keep-stone": "PF2E.PreciousMaterialKeepStone",
    noqual: "PF2E.PreciousMaterialNoqual",
    orichalcum: "PF2E.PreciousMaterialOrichalcum",
    peachwood: "PF2E.PreciousMaterialPeachwood",
    siccatite: "PF2E.PreciousMaterialSiccatite",
    silver: "PF2E.PreciousMaterialSilver",
    sisterstone: "PF2E.PreciousMaterialSisterstone",
    "sisterstone-dusk": "PF2E.PreciousMaterialSisterstoneDusk",
    "sisterstone-scarlet": "PF2E.PreciousMaterialSisterstoneScarlet",
    sloughstone: "PF2E.PreciousMaterialSloughstone",
    "sovereign-steel": "PF2E.PreciousMaterialSovereignSteel",
    warpglass: "PF2E.PreciousMaterialWarpglass",
};

const otherArmorTags: Record<OtherArmorTag, string> = {
    shoddy: "PF2E.Item.Physical.OtherTag.Shoddy",
};

const otherConsumableTags: Record<OtherConsumableTag, string> = {
    "alchemical-food": "PF2E.Item.Physical.OtherTag.AlchemicalFood",
    "alchemical-tool": "PF2E.Item.Physical.OtherTag.AlchemicalTool",
    herbal: "PF2E.Item.Physical.OtherTag.Herbal",
};

const otherWeaponTags: Record<OtherWeaponTag, string> = {
    "handwraps-of-mighty-blows": "PF2E.Item.Physical.OtherTag.HandwrapsOfMightyBlows",
    improvised: "PF2E.Item.Physical.OtherTag.Improvised",
    shoddy: "PF2E.Item.Physical.OtherTag.Shoddy",
};

const npcAttackTraits = {
    ...weaponTraits,
    ...preciousMaterials,
    area: "PF2E.TraitArea",
    concentrate: "PF2E.TraitConcentrate",
    curse: "PF2E.TraitCurse",
    "deadly-2d8": "PF2E.TraitDeadly2D8",
    "deadly-3d8": "PF2E.TraitDeadly3D8",
    "deadly-4d8": "PF2E.TraitDeadly4D8",
    "deadly-2d10": "PF2E.TraitDeadly2D10",
    "deadly-3d10": "PF2E.TraitDeadly3D10",
    "deadly-4d10": "PF2E.TraitDeadly4D10",
    "deadly-2d12": "PF2E.TraitDeadly2D12",
    "deadly-3d12": "PF2E.TraitDeadly3D12",
    "deadly-4d12": "PF2E.TraitDeadly4D12",
    illusion: "PF2E.TraitIllusion",
    impulse: "PF2E.TraitImpulse",
    incorporeal: "PF2E.TraitIncorporeal",
    radiation: "PF2E.TraitRadiation",
    "reach-0": "PF2E.TraitReach0",
    "reach-10": "PF2E.TraitReach10",
    "reach-15": "PF2E.TraitReach15",
    "reach-20": "PF2E.TraitReach20",
    "reach-25": "PF2E.TraitReach25",
    "reach-30": "PF2E.TraitReach30",
    "reach-40": "PF2E.TraitReach40",
    "reach-50": "PF2E.TraitReach50",
    "reach-60": "PF2E.TraitReach60",
    "reach-100": "PF2E.TraitReach100",
    "reach-120": "PF2E.TraitReach120",
    "reach-200": "PF2E.TraitReach200",
    "reach-1000": "PF2E.TraitReach1000",
    "reload-0": "PF2E.TraitReload0",
    "reload-1": "PF2E.TraitReload1",
    "reload-2": "PF2E.TraitReload2",
    "reload-1-min": "PF2E.TraitReload1Min",
    sanctified: "PF2E.TraitSanctified",
};

const featTraits = {
    ...ancestryTraits,
    ...classTraits,
    ...damageTraits,
    ...magicTraditions,
    ...spellTraits,
    additive: "PF2E.TraitAdditive",
    additive1: "PF2E.TraitAdditive1",
    additive2: "PF2E.TraitAdditive2",
    additive3: "PF2E.TraitAdditive3",
    aftermath: "PF2E.TraitAftermath",
    alchemical: "PF2E.TraitAlchemical",
    apparition: "PF2E.TraitApparition",
    archetype: "PF2E.TraitArchetype",
    artifact: "PF2E.TraitArtifact",
    auditory: "PF2E.TraitAuditory",
    aura: "PF2E.TraitAura",
    brandish: "PF2E.TraitBrandish",
    bravado: "PF2E.TraitBravado",
    calling: "PF2E.TraitCalling",
    circus: "PF2E.TraitCircus",
    class: "TYPES.Item.class",
    coagulant: "PF2E.TraitCoagulant",
    composite: "PF2E.TraitComposite",
    concentrate: "PF2E.TraitConcentrate",
    dedication: "PF2E.TraitDedication",
    destiny: "PF2E.TraitDestiny",
    detection: "PF2E.TraitDetection",
    deviant: "PF2E.TraitDeviant",
    downtime: "PF2E.TraitDowntime",
    emotion: "PF2E.TraitEmotion",
    evolution: "PF2E.TraitEvolution",
    esoterica: "PF2E.TraitEsoterica",
    exploration: "PF2E.TraitExploration",
    fear: "PF2E.TraitFear",
    finisher: "PF2E.TraitFinisher",
    flourish: "PF2E.TraitFlourish",
    fortune: "PF2E.TraitFortune",
    general: "PF2E.TraitGeneral",
    ikon: "PF2E.TraitIkon",
    impulse: "PF2E.TraitImpulse",
    infusion: "PF2E.TraitInfusion",
    injury: "PF2E.TraitInjury",
    lineage: "PF2E.TraitLineage",
    manipulate: "PF2E.TraitManipulate",
    mindshift: "PF2E.TraitMindshift",
    modification: "PF2E.TraitModification",
    move: "PF2E.TraitMove",
    multiclass: "PF2E.TraitMulticlass",
    oath: "PF2E.TraitOath",
    olfactory: "PF2E.TraitOlfactory",
    overflow: "PF2E.TraitOverflow",
    "pervasive-magic": "PF2E.TraitPervasiveMagic",
    poison: "PF2E.TraitPoison",
    press: "PF2E.TraitPress",
    rage: "PF2E.TraitRage",
    reckless: "PF2E.TraitReckless",
    reincarnated: "PF2E.TraitReincarnated",
    reflection: "PF2E.TraitReflection",
    secret: "PF2E.TraitSecret",
    skill: "PF2E.TraitSkill",
    social: "PF2E.TraitSocial",
    spellshot: "PF2E.TraitSpellshot",
    stamina: "PF2E.TraitStamina",
    stance: "PF2E.TraitStance",
    tactic: "PF2E.TraitTactic",
    talisman: "PF2E.TraitTalisman",
    tandem: "PF2E.TraitTandem",
    time: "PF2E.TraitTime",
    transcendence: "PF2E.TraitTranscendence",
    "true-name": "PF2E.TraitTrueName",
    unstable: "PF2E.TraitUnstable",
    vigilante: "PF2E.TraitVigilante",
    virulent: "PF2E.TraitVirulent",
    vitality: "PF2E.TraitVitality",
    void: "PF2E.TraitVoid",
    wandering: "PF2E.TraitWandering",
};

const consumableTraits = {
    ...spellTraits,
    additive: "PF2E.TraitAdditive",
    additive1: "PF2E.TraitAdditive1",
    additive2: "PF2E.TraitAdditive2",
    additive3: "PF2E.TraitAdditive3",
    alchemical: "PF2E.TraitAlchemical",
    attack: "PF2E.TraitAttack",
    auditory: "PF2E.TraitAuditory",
    aura: "PF2E.TraitAura",
    "bottled-breath": "PF2E.TraitBottledBreath",
    catalyst: "PF2E.TraitCatalyst",
    coagulant: "PF2E.TraitCoagulant",
    clockwork: "PF2E.TraitClockwork",
    consumable: "PF2E.TraitConsumable",
    contact: "PF2E.TraitContact",
    curse: "PF2E.TraitCurse",
    cursed: "PF2E.TraitCursed",
    drug: "PF2E.TraitDrug",
    elixir: "PF2E.TraitElixir",
    emotion: "PF2E.TraitEmotion",
    expandable: "PF2E.TraitExpandable",
    fear: "PF2E.TraitFear",
    fey: "PF2E.TraitFey",
    fortune: "PF2E.TraitFortune",
    fulu: "PF2E.TraitFulu",
    gadget: "PF2E.TraitGadget",
    healing: "PF2E.TraitHealing",
    incapacitation: "PF2E.TraitIncapacitation",
    infused: "PF2E.TraitInfused",
    ingested: "PF2E.TraitIngested",
    inhaled: "PF2E.TraitInhaled",
    injury: "PF2E.TraitInjury",
    kobold: "PF2E.TraitKobold",
    light: "PF2E.TraitLight",
    linguistic: "PF2E.TraitLinguistic",
    lozenge: "PF2E.TraitLozenge",
    magical: "PF2E.TraitMagical",
    mechanical: "PF2E.TraitMechanical",
    misfortune: "PF2E.TraitMisfortune",
    missive: "PF2E.TraitMissive",
    morph: "PF2E.TraitMorph",
    mutagen: "PF2E.TraitMutagen",
    oil: "PF2E.TraitOil",
    olfactory: "PF2E.TraitOlfactory",
    poison: "PF2E.TraitPoison",
    polymorph: "PF2E.TraitPolymorph",
    possession: "PF2E.TraitPossession",
    potion: "PF2E.TraitPotion",
    precious: "PF2E.TraitPrecious",
    processed: "PF2E.TraitProcessed",
    scroll: "PF2E.TraitScroll",
    scrying: "PF2E.TraitScrying",
    spirit: "PF2E.TraitSpirit",
    sleep: "PF2E.TraitSleep",
    snare: "PF2E.TraitSnare",
    spellgun: "PF2E.TraitSpellgun",
    splash: "PF2E.TraitSplash",
    structure: "PF2E.TraitStructure",
    talisman: "PF2E.TraitTalisman",
    tea: "PF2E.TraitTea",
    teleportation: "PF2E.TraitTeleportation",
    trap: "PF2E.TraitTrap",
    virulent: "PF2E.TraitVirulent",
    visual: "PF2E.TraitVisual",
    wand: "PF2E.TraitWand",
    whetstone: "PF2E.TraitWhetstone",
};

const weaponActionTraits = R.pick(weaponTraits, [
    "agile",
    "propulsive",
    "backswing",
    "forceful",
    "reach",
    "sweep",
    "thrown",
    "volley-20",
    "volley-30",
    "volley-50",
    "volley-60",
]);

const actionTraits = {
    ...featTraits,
    ...consumableTraits,
    ...spellTraits,
    ...weaponActionTraits,
    "certain-kill": "PF2E.TraitCertainKill",
    summon: "PF2E.TraitSummon",
};

const effectTraits = R.omit(actionTraits, [
    ...R.keys(ancestryTraits),
    ...R.keys(classTraits),
    ...R.keys(weaponActionTraits),
    "additive",
    "additive1",
    "additive2",
    "additive3",
    "aftermath",
    "amp",
    "archetype",
    "attack",
    "backswing",
    "beast",
    "bottled-breath",
    "cantrip",
    "catalyst",
    "circus",
    "class",
    "clockwork",
    "coagulant",
    "composite",
    "composition",
    "concentrate",
    "consumable",
    "dedication",
    "deviant",
    "eidolon",
    "elixir",
    "esoterica",
    "expandable",
    "exploration",
    "finisher",
    "flourish",
    "focus",
    "forceful",
    "fulu",
    "gadget",
    "general",
    "infused",
    "lineage",
    "litany",
    "lozenge",
    "manipulate",
    "missive",
    "modification",
    "multiclass",
    "mutagen",
    "oath",
    "oil",
    "overflow",
    "pervasive-magic",
    "potion",
    "precious",
    "press",
    "processed",
    "propulsive",
    "reckless",
    "reincarnated",
    "revelation",
    "sanctified",
    "scroll",
    "secret",
    "skill",
    "snare",
    "spellgun",
    "splash",
    "structure",
    "subtle",
    "talisman",
    "tandem",
    "tea",
    "trap",
    "unstable",
    "vigilante",
    "wand",
] as const);

const hazardTraits = {
    ...creatureTraits,
    ...damageTraits,
    ...magicTraditions,
    alchemical: "PF2E.TraitAlchemical",
    auditory: "PF2E.TraitAuditory",
    consumable: "PF2E.TraitConsumable",
    curse: "PF2E.TraitCurse",
    environmental: "PF2E.TraitEnvironmental",
    haunt: "PF2E.TraitHaunt",
    inhaled: "PF2E.TraitInhaled",
    kaiju: "PF2E.TraitKaiju",
    mechanical: "PF2E.TraitMechanical",
    nightmare: "PF2E.TraitNightmare",
    poison: "PF2E.TraitPoison",
    polymorph: "PF2E.TraitPolymorph",
    snare: "PF2E.TraitSnare",
    steam: "PF2E.TraitSteam",
    technological: "PF2E.TraitTechnological",
    teleportation: "PF2E.TraitTeleportation",
    trap: "PF2E.TraitTrap",
    virulent: "PF2E.TraitVirulent",
    visual: "PF2E.TraitVisual",
};

const vehicleTraits = {
    artifact: "PF2E.TraitArtifact",
    clockwork: "PF2E.TraitClockwork",
    magical: "PF2E.TraitMagical",
    tech: "PF2E.TraitTech",
    teleportation: "PF2E.TraitTeleportation",
};

const equipmentTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    additive: "PF2E.TraitAdditive",
    additive0: "PF2E.TraitAdditive0",
    additive1: "PF2E.TraitAdditive1",
    adjusted: "PF2E.TraitAdjusted",
    adjustment: "PF2E.TraitAdjustment",
    alchemical: "PF2E.TraitAlchemical",
    analog: "PF2E.TraitAnalog",
    apex: "PF2E.TraitApex",
    artifact: "PF2E.TraitArtifact",
    auditory: "PF2E.TraitAuditory",
    aura: "PF2E.TraitAura",
    barding: "PF2E.TraitBarding",
    censer: "PF2E.TraitCenser",
    clockwork: "PF2E.TraitClockwork",
    coagulant: "PF2E.TraitCoagulant",
    coda: "PF2E.TraitCoda",
    companion: "PF2E.TraitCompanion",
    consecration: "PF2E.TraitConsecration",
    contract: "PF2E.TraitContract",
    cursed: "PF2E.TraitCursed",
    darkness: "PF2E.TraitDarkness",
    death: "PF2E.TraitDeath",
    detection: "PF2E.TraitDetection",
    dream: "PF2E.TraitDream",
    eidolon: "PF2E.TraitEidolon",
    emotion: "PF2E.TraitEmotion",
    expandable: "PF2E.TraitExpandable",
    extradimensional: "PF2E.TraitExtradimensional",
    fear: "PF2E.TraitFear",
    figurehead: "PF2E.TraitFigurehead",
    focused: "PF2E.TraitFocused",
    fortune: "PF2E.TraitFortune",
    fulu: "PF2E.TraitFulu",
    gadget: "PF2E.TraitGadget",
    graft: "PF2E.TraitGraft",
    grimoire: "PF2E.TraitGrimoire",
    "harrow-court": "PF2E.TraitHarrowCourt",
    healing: "PF2E.TraitHealing",
    illusion: "PF2E.TraitIllusion",
    incapacitation: "PF2E.TraitIncapacitation",
    incorporeal: "PF2E.TraitIncorporeal",
    infused: "PF2E.TraitInfused",
    intelligent: "PF2E.TraitIntelligent",
    invested: "PF2E.TraitInvested",
    light: "PF2E.TraitLight",
    magical: "PF2E.TraitMagical",
    mechanical: "PF2E.TraitMechanical",
    mental: "PF2E.TraitMental",
    misfortune: "PF2E.TraitMisfortune",
    morph: "PF2E.TraitMorph",
    mounted: "PF2E.TraitMounted",
    mythic: "PF2E.TraitMythic",
    nonlethal: "PF2E.TraitNonlethal",
    plant: "PF2E.TraitPlant",
    poison: "PF2E.TraitPoison",
    polymorph: "PF2E.TraitPolymorph",
    portable: "PF2E.TraitPortable",
    precious: "PF2E.TraitPrecious",
    prediction: "PF2E.TraitPrediction",
    relic: "PF2E.TraitRelic",
    revelation: "PF2E.TraitRevelation",
    saggorak: "PF2E.TraitSaggorak",
    scrying: "PF2E.TraitScrying",
    shadow: "PF2E.TraitShadow",
    sleep: "PF2E.TraitSleep",
    spellgun: "PF2E.TraitSpellgun",
    spellheart: "PF2E.TraitSpellheart",
    spirit: "PF2E.TraitSpirit",
    staff: "PF2E.TraitStaff",
    steam: "PF2E.TraitSteam",
    structure: "PF2E.TraitStructure",
    tattoo: "PF2E.TraitTattoo",
    tech: "PF2E.TraitTech",
    teleportation: "PF2E.TraitTeleportation",
    visual: "PF2E.TraitVisual",
    wand: "PF2E.TraitWand",
};

const shieldTraits = {
    ...sanctificationTraits,
    ...damageTraits,
    ...magicTraditions,
    alchemical: "PF2E.TraitAlchemical",
    analog: "PF2E.TraitAnalog",
    apex: "PF2E.TraitApex",
    artifact: "PF2E.TraitArtifact",
    aura: "PF2E.TraitAura",
    "deflecting-bludgeoning": "PF2E.TraitDeflectingBludgeoning",
    "deflecting-physical-ranged": "PF2E.TraitDeflectingPhysicalRanged",
    "deflecting-piercing": "PF2E.TraitDeflectingPiercing",
    "deflecting-slashing": "PF2E.TraitDeflectingSlashing",
    foldaway: "PF2E.TraitFoldaway",
    harnessed: "PF2E.TraitHarnessed",
    "hefty-2": "PF2E.TraitHefty2",
    inscribed: "PF2E.TraitInscribed",
    "integrated-1d6-b": "PF2E.TraitIntegrated1d6B",
    "integrated-1d6-p": "PF2E.TraitIntegrated1d6P",
    "integrated-1d6-s": "PF2E.TraitIntegrated1d6S",
    "integrated-1d6-s-versatile-p": "PF2E.TraitIntegrated1d6SVersatileP",
    invested: "PF2E.TraitInvested",
    "launching-dart": "PF2E.TraitLaunching",
    magical: "PF2E.TraitMagical",
    mythic: "PF2E.TraitMythic",
    relic: "PF2E.TraitRelic",
    "shield-throw-20": "PF2E.TraitShieldThrow20",
    "shield-throw-30": "PF2E.TraitShieldThrow30",
    tech: "PF2E.TraitTech",
};

const armorTraits = {
    ...sanctificationTraits,
    ...damageTraits,
    ...magicTraditions,
    adjusted: "PF2E.TraitAdjusted",
    alchemical: "PF2E.TraitAlchemical",
    analog: "PF2E.TraitAnalog",
    apex: "PF2E.TraitApex",
    aquadynamic: "PF2E.TraitAquadynamic",
    artifact: "PF2E.TraitArtifact",
    auditory: "PF2E.TraitAuditory",
    aura: "PF2E.TraitAura",
    barding: "PF2E.TraitBarding",
    bulwark: "PF2E.TraitBulwark",
    clockwork: "PF2E.TraitClockwork",
    comfort: "PF2E.TraitComfort",
    companion: "PF2E.TraitCompanion",
    cursed: "PF2E.TraitCursed",
    "entrench-melee": "PF2E.TraitEntrenchMelee",
    "entrench-ranged": "PF2E.TraitEntrenchRanged",
    extradimensional: "PF2E.TraitExtradimensional",
    flexible: "PF2E.TraitFlexible",
    focused: "PF2E.TraitFocused",
    force: "PF2E.TraitForce",
    healing: "PF2E.TraitHealing",
    hindering: "PF2E.TraitHindering",
    illusion: "PF2E.TraitIllusion",
    inscribed: "PF2E.TraitInscribed",
    intelligent: "PF2E.TraitIntelligent",
    invested: "PF2E.TraitInvested",
    laminar: "PF2E.TraitLaminar",
    light: "PF2E.TraitLight",
    magical: "PF2E.TraitMagical",
    mythic: "PF2E.TraitMythic",
    noisy: "PF2E.TraitNoisy",
    plant: "PF2E.TraitPlant",
    ponderous: "PF2E.TraitPonderous",
    relic: "PF2E.TraitRelic",
    "resilient-1": "PF2E.TraitResilient1",
    "resilient-2": "PF2E.TraitResilient2",
    "resilient-3": "PF2E.TraitResilient3",
    tech: "PF2E.TraitTech",
};

const kingmakerTraits = {
    ...actionTraits,
    army: "PF2E.Kingmaker.Trait.army",
    cavalry: "PF2E.Kingmaker.Trait.cavalry",
    civic: "PF2E.Kingmaker.Trait.civic",
    commerce: "PF2E.Kingmaker.Trait.commerce",
    infantry: "PF2E.Kingmaker.Trait.infantry",
    kingdom: "PF2E.Kingmaker.Trait.kingdom",
    leadership: "PF2E.Kingmaker.Trait.leadership",
    maneuver: "PF2E.Kingmaker.Trait.maneuver",
    morale: "PF2E.Kingmaker.Trait.morale",
    region: "PF2E.Kingmaker.Trait.region",
    siege: "PF2E.Kingmaker.Trait.siege",
    skirmisher: "PF2E.Kingmaker.Trait.skirmisher",
    upkeep: "PF2E.Kingmaker.Trait.upkeep",
};

const kingmakerDescriptions = {
    cavalry: "PF2E.Kingmaker.TraitDescription.cavalry",
    infantry: "PF2E.Kingmaker.TraitDescription.infantry",
    siege: "PF2E.Kingmaker.TraitDescription.siege",
    skirmisher: "PF2E.Kingmaker.TraitDescription.skirmisher",
};

const preciousMaterialDescriptions = {
    abysium: "PF2E.PreciousMaterialAbysiumDescription",
    adamantine: "PF2E.PreciousMaterialAdamantineDescription",
    "cold-iron": "PF2E.PreciousMaterialColdIronDescription",
    duskwood: "PF2E.PreciousMaterialDuskwoodDescription",
    djezet: "PF2E.PreciousMaterialDjezetDescription",
    dragonhide: "PF2E.PreciousMaterialDragonhideDescription",
    dreamweb: "PF2E.PreciousMaterialDreamwebDescription",
    "grisantian-pelt": "PF2E.PreciousMaterialGrisantianPeltDescription",
    inubrix: "PF2E.PreciousMaterialInubrixDescription",
    dawnsilver: "PF2E.PreciousMaterialDawnsilverDescription",
    noqual: "PF2E.PreciousMaterialNoqualDescription",
    orichalcum: "PF2E.PreciousMaterialOrichalcumDescription",
    siccatite: "PF2E.PreciousMaterialSiccatiteDescription",
    silver: "PF2E.PreciousMaterialSilverDescription",
    sisterstone: "PF2E.PreciousMaterialSisterstoneDescription",
    "sisterstone-dusk": "PF2E.PreciousMaterialSisterstoneDescription",
    "sisterstone-scarlet": "PF2E.PreciousMaterialSisterstoneDescription",
    sloughstone: "PF2E.PreciousMaterialSloughstoneDescription",
    "sovereign-steel": "PF2E.PreciousMaterialSovereignSteelDescription",
    warpglass: "PF2E.PreciousMaterialWarpglassDescription",
};

const traitDescriptions = {
    ...kingmakerDescriptions,
    aasimar: "PF2E.TraitDescriptionAasimar",
    aberration: "PF2E.TraitDescriptionAberration",
    abjuration: "PF2E.TraitDescriptionAbjuration",
    acid: "PF2E.TraitDescriptionAcid",
    additive: "PF2E.TraitDescriptionAdditive",
    additive0: "PF2E.TraitDescriptionAdditive",
    additive1: "PF2E.TraitDescriptionAdditive",
    additive2: "PF2E.TraitDescriptionAdditive",
    additive3: "PF2E.TraitDescriptionAdditive",
    adjusted: "PF2E.TraitDescriptionAdjusted",
    adjustment: "PF2E.TraitDescriptionAdjustment",
    aeon: "PF2E.TraitDescriptionAeon",
    aesir: "PF2E.TraitDescriptionAesir",
    aftermath: "PF2E.TraitDescriptionAftermath",
    agathion: "PF2E.TraitDescriptionAgathion",
    agile: "PF2E.TraitDescriptionAgile",
    air: "PF2E.TraitDescriptionAir",
    aiuvarin: "PF2E.TraitDescriptionAiuvarin",
    alchemical: "PF2E.TraitDescriptionAlchemical",
    alchemist: "PF2E.TraitDescriptionAlchemist",
    amphibious: "PF2E.TraitDescriptionAmphibious",
    anadi: "PF2E.TraitDescriptionAnadi",
    analog: "PF2E.TraitDescriptionAnalog",
    android: "PF2E.TraitDescriptionAndroid",
    angel: "PF2E.TraitDescriptionAngel",
    animal: "PF2E.TraitDescriptionAnimal",
    animist: "PF2E.TraitDescriptionAnimist",
    apex: "PF2E.TraitDescriptionApex",
    aphorite: "PF2E.TraitDescriptionAphorite",
    apparition: "PF2E.TraitDescriptionApparition",
    aquadynamic: "PF2E.TraitDescriptionAquadynamic",
    aquatic: "PF2E.TraitDescriptionAquatic",
    arcane: "PF2E.TraitDescriptionArcane",
    archetype: "PF2E.TraitDescriptionArchetype",
    archon: "PF2E.TraitDescriptionArchon",
    ardande: "PF2E.TraitDescriptionArdande",
    astral: "PF2E.TraitDescriptionAstral",
    asura: "PF2E.TraitDescriptionAsura",
    artifact: "PF2E.TraitDescriptionArtifact",
    athamaru: "PF2E.TraitDescriptionAthamaru",
    attached: "PF2E.TraitDescriptionAttached",
    "attached-to-crossbow-or-firearm": "PF2E.TraitDescriptionAttached",
    "attached-to-shield": "PF2E.TraitDescriptionAttached",
    attack: "PF2E.TraitDescriptionAttack",
    auditory: "PF2E.TraitDescriptionAuditory",
    aura: "PF2E.TraitDescriptionAura",
    automaton: "PF2E.TraitDescriptionAutomaton",
    "awakened-animal": "PF2E.TraitDescriptionAwakenedAnimal",
    azarketi: "PF2E.TraitDescriptionAzarketi",
    azata: "PF2E.TraitDescriptionAzata",
    backstabber: "PF2E.TraitDescriptionBackstabber",
    backswing: "PF2E.TraitDescriptionBackswing",
    barbarian: "PF2E.TraitDescriptionBarbarian",
    bard: "PF2E.TraitDescriptionBard",
    beast: "PF2E.TraitDescriptionBeast",
    beastkin: "PF2E.TraitDescriptionBeastkin",
    blight: "PF2E.TraitDescriptionBlight",
    boggard: "PF2E.TraitDescriptionBoggard",
    bomb: "PF2E.TraitDescriptionBomb",
    "bottled-breath": "PF2E.TraitDescriptionBottledBreath",
    brace: "PF2E.TraitDescriptionBrace",
    brutal: "PF2E.TraitDescriptionBrutal",
    bugbear: "PF2E.TraitDescriptionBugbear",
    bulwark: "PF2E.TraitDescriptionBulwark",
    bravado: "PF2E.TraitDescriptionBravado",
    caligni: "PF2E.TraitDescriptionCaligni",
    calling: "PF2E.TraitDescriptionCalling",
    cantrip: "PF2E.TraitDescriptionCantrip",
    "capacity-2": "PF2E.TraitDescriptionCapacity",
    "capacity-3": "PF2E.TraitDescriptionCapacity",
    "capacity-4": "PF2E.TraitDescriptionCapacity",
    "capacity-5": "PF2E.TraitDescriptionCapacity",
    catalyst: "PF2E.TraitDescriptionCatalyst",
    celestial: "PF2E.TraitDescriptionCelestial",
    catfolk: "PF2E.TraitDescriptionCatfolk",
    censer: "PF2E.TraitDescriptionCenser",
    centaur: "PF2E.TraitDescriptionCentaur",
    "certain-kill": "PF2E.TraitDescriptionCertainKill",
    champion: "PF2E.TraitDescriptionChampion",
    changeling: "PF2E.TraitDescriptionChangeling",
    "charau-ka": "PF2E.TraitDescriptionCharauKa",
    class: "PF2E.TraitDescriptionClass",
    cleric: "PF2E.TraitDescriptionCleric",
    climbing: "PF2E.TraitDescriptionClimbing",
    clockwork: "PF2E.TraitDescriptionClockwork",
    coatl: "PF2E.TraitDescriptionCoatl",
    cobbled: "PF2E.TraitDescriptionCobbled",
    coagulant: "PF2E.TraitDescriptionCoagulant",
    coda: "PF2E.TraitDescriptionCoda",
    cold: "PF2E.TraitDescriptionCold",
    combination: "PF2E.TraitDescriptionCombination",
    comfort: "PF2E.TraitDescriptionComfort",
    common: "PF2E.TraitDescriptionCommon",
    companion: "PF2E.TraitDescriptionCompanion",
    complex: "PF2E.TraitDescriptionComplex",
    composite: "PF2E.TraitDescriptionComposite",
    composition: "PF2E.TraitDescriptionComposition",
    concealable: "PF2E.TraitDescriptionConcealable",
    concentrate: "PF2E.TraitDescriptionConcentrate",
    concussive: "PF2E.TraitDescriptionConcussive",
    conrasu: "PF2E.TraitDescriptionConrasu",
    consecration: "PF2E.TraitDescriptionConsecration",
    construct: "PF2E.TraitDescriptionConstruct",
    consumable: "PF2E.TraitDescriptionConsumable",
    contact: "PF2E.TraitDescriptionContact",
    contingency: "PF2E.TraitDescriptionContingency",
    contract: "PF2E.TraitDescriptionContract",
    "critical-fusion": "PF2E.TraitDescriptionCriticalFusion",
    curse: "PF2E.TraitDescriptionCurse",
    cursebound: "PF2E.TraitDescriptionCursebound",
    cursed: "PF2E.TraitDescriptionCursed",
    daemon: "PF2E.TraitDescriptionDaemon",
    darkness: "PF2E.TraitDescriptionDarkness",
    darvakka: "PF2E.TraitDescriptionDarvakka",
    "deadly-2d10": "PF2E.TraitDescriptionDeadly",
    "deadly-2d12": "PF2E.TraitDescriptionDeadly",
    "deadly-2d8": "PF2E.TraitDescriptionDeadly",
    "deadly-3d10": "PF2E.TraitDescriptionDeadly",
    "deadly-3d12": "PF2E.TraitDescriptionDeadly",
    "deadly-3d8": "PF2E.TraitDescriptionDeadly",
    "deadly-4d10": "PF2E.TraitDescriptionDeadly",
    "deadly-4d12": "PF2E.TraitDescriptionDeadly",
    "deadly-4d8": "PF2E.TraitDescriptionDeadly",
    "deadly-d10": "PF2E.TraitDescriptionDeadly",
    "deadly-d12": "PF2E.TraitDescriptionDeadly",
    "deadly-d6": "PF2E.TraitDescriptionDeadly",
    "deadly-d8": "PF2E.TraitDescriptionDeadly",
    "deadly-d4": "PF2E.TraitDescriptionDeadly",
    death: "PF2E.TraitDescriptionDeath",
    "deflecting-bludgeoning": "PF2E.TraitDescriptionDeflecting",
    "deflecting-physical-ranged": "PF2E.TraitDescriptionDeflecting",
    "deflecting-slashing": "PF2E.TraitDescriptionDeflecting",
    dedication: "PF2E.TraitDescriptionDedication",
    demon: "PF2E.TraitDescriptionDemon",
    dero: "PF2E.TraitDescriptionDero",
    destiny: "PF2E.TraitDescriptionDestiny",
    detection: "PF2E.TraitDescriptionDetection",
    deviant: "PF2E.TraitDescriptionDeviant",
    devil: "PF2E.TraitDescriptionDevil",
    dhampir: "PF2E.TraitDescriptionDhampir",
    dinosaur: "PF2E.TraitDescriptionDinosaur",
    disarm: "PF2E.TraitDescriptionDisarm",
    disease: "PF2E.TraitDescriptionDisease",
    divination: "PF2E.TraitDescriptionDivination",
    div: "PF2E.TraitDescriptionDiv",
    divine: "PF2E.TraitDescriptionDivine",
    "double-barrel": "PF2E.TraitDescriptionDoubleBarrel",
    downtime: "PF2E.TraitDescriptionDowntime",
    dragon: "PF2E.TraitDescriptionDragon",
    dragonblood: "PF2E.TraitDescriptionDragonblood",
    dragonet: "PF2E.TraitDescriptionDragonet",
    dream: "PF2E.TraitDescriptionDream",
    dromaar: "PF2E.TraitDescriptionDromaar",
    drug: "PF2E.TraitDescriptionDrug",
    druid: "PF2E.TraitDescriptionDruid",
    duskwalker: "PF2E.TraitDescriptionDuskwalker",
    dwarf: "PF2E.TraitDescriptionDwarf",
    earth: "PF2E.TraitDescriptionEarth",
    eidolon: "PF2E.TraitDescriptionEidolon",
    electricity: "PF2E.TraitDescriptionElectricity",
    elemental: "PF2E.TraitDescriptionElemental",
    elf: "PF2E.TraitDescriptionElf",
    elixir: "PF2E.TraitDescriptionElixir",
    emotion: "PF2E.TraitDescriptionEmotion",
    "entrench-melee": "PF2E.TraitDescriptionEntrench",
    "entrench-ranged": "PF2E.TraitDescriptionEntrench",
    environmental: "PF2E.TraitDescriptionEnvironmental",
    esoterica: "PF2E.TraitDescriptionEsoterica",
    ethereal: "PF2E.TraitDescriptionEthereal",
    evolution: "PF2E.TraitDescriptionEvolution",
    exemplar: "PF2E.TraitDescriptionExemplar",
    expandable: "PF2E.TraitDescriptionExpandable",
    experiment: "PF2E.TraitDescriptionExperiment",
    exploration: "PF2E.TraitDescriptionExploration",
    extradimensional: "PF2E.TraitDescriptionExtradimensional",
    "fatal-aim-d10": "PF2E.TraitDescriptionFatalAim",
    "fatal-aim-d12": "PF2E.TraitDescriptionFatalAim",
    "fatal-d10": "PF2E.TraitDescriptionFatal",
    "fatal-d12": "PF2E.TraitDescriptionFatal",
    "fatal-d8": "PF2E.TraitDescriptionFatal",
    fear: "PF2E.TraitDescriptionFear",
    fetchling: "PF2E.TraitDescriptionFetchling",
    fey: "PF2E.TraitDescriptionFey",
    fiend: "PF2E.TraitDescriptionFiend",
    fighter: "PF2E.TraitDescriptionFighter",
    figurehead: "PF2E.TraitDescriptionFigurehead",
    finesse: "PF2E.TraitDescriptionFinesse",
    finisher: "PF2E.TraitDescriptionFinisher",
    fire: "PF2E.TraitDescriptionFire",
    fleshwarp: "PF2E.TraitDescriptionFleshwarp",
    flexible: "PF2E.TraitDescriptionFlexible",
    flourish: "PF2E.TraitDescriptionFlourish",
    focus: "PF2E.TraitDescriptionFocus",
    focused: "PF2E.TraitDescriptionFocused",
    foldaway: "PF2E.TraitDescriptionFoldaway",
    force: "PF2E.TraitDescriptionForce",
    forceful: "PF2E.TraitDescriptionForceful",
    fortune: "PF2E.TraitDescriptionFortune",
    "free-hand": "PF2E.TraitDescriptionFreeHand",
    fulu: "PF2E.TraitDescriptionFulu",
    fungus: "PF2E.TraitDescriptionFungus",
    gadget: "PF2E.TraitDescriptionGadget",
    ganzi: "PF2E.TraitDescriptionGanzi",
    graft: "PF2E.TraitDescriptionGraft",
    general: "PF2E.TraitDescriptionGeneral",
    genie: "PF2E.TraitDescriptionGenie",
    geniekin: "PF2E.TraitDescriptionGeniekin",
    ghoran: "PF2E.TraitDescriptionGhoran",
    ghost: "PF2E.TraitDescriptionGhost",
    ghoul: "PF2E.TraitDescriptionGhoul",
    ghul: "PF2E.TraitDescriptionGhul",
    giant: "PF2E.TraitDescriptionGiant",
    girtablilu: "PF2E.TraitDescriptionGirtablilu",
    gnoll: "PF2E.TraitDescriptionGnoll",
    gnome: "PF2E.TraitDescriptionGnome",
    goblin: "PF2E.TraitDescriptionGoblin",
    goloma: "PF2E.TraitDescriptionGoloma",
    grapple: "PF2E.TraitDescriptionGrapple",
    gremlin: "PF2E.TraitDescriptionGremlin",
    grimoire: "PF2E.TraitDescriptionGrimoire",
    grippli: "PF2E.TraitDescriptionGrippli",
    grioth: "PF2E.TraitDescriptionGrioth",
    gunslinger: "PF2E.TraitDescriptionGunslinger",
    hag: "PF2E.TraitDescriptionHag",
    halfling: "PF2E.TraitDescriptionHalfling",
    "jousting-d4": "PF2E.TraitDescriptionJousting",
    "jousting-d6": "PF2E.TraitDescriptionJousting",
    "jousting-d8": "PF2E.TraitDescriptionJousting",
    "jousting-d10": "PF2E.TraitDescriptionJousting",
    hampering: "PF2E.TraitDescriptionHampering",
    harnessed: "PF2E.TraitDescriptionHarnessed",
    haunt: "PF2E.TraitDescriptionHaunt",
    healing: "PF2E.TraitDescriptionHealing",
    "hefty-14": "PF2E.TraitDescriptionHefty",
    herald: "PF2E.TraitDescriptionHerald",
    hex: "PF2E.TraitDescriptionHex",
    hindering: "PF2E.TraitDescriptionHindering",
    hobgoblin: "PF2E.TraitDescriptionHobgoblin",
    holy: "PF2E.TraitDescriptionHoly",
    hryngar: "PF2E.TraitDescriptionHryngar",
    human: "PF2E.TraitDescriptionHuman",
    humanoid: "PF2E.TraitDescriptionHumanoid",
    naari: "PF2E.TraitDescriptionNaari",
    nightmare: "PF2E.TraitDescriptionNightmare",
    ikon: "PF2E.TraitDescriptionIkon",
    illusion: "PF2E.TraitDescriptionIllusion",
    impulse: "PF2E.TraitDescriptionImpulse",
    incapacitation: "PF2E.TraitDescriptionIncapacitation",
    incarnate: "PF2E.TraitDescriptionIncarnate",
    incorporeal: "PF2E.TraitDescriptionIncorporeal",
    inevitable: "PF2E.TraitDescriptionInevitable",
    infused: "PF2E.TraitDescriptionInfused",
    infusion: "PF2E.TraitDescriptionInfusion",
    ingested: "PF2E.TraitDescriptionIngested",
    inhaled: "PF2E.TraitDescriptionInhaled",
    injection: "PF2E.TraitDescriptionInjection",
    injury: "PF2E.TraitDescriptionInjury",
    inscribed: "PF2E.TraitDescriptionInscribed",
    "integrated-1d6-b": "PF2E.TraitDescriptionIntegrated",
    "integrated-1d6-p": "PF2E.TraitDescriptionIntegrated",
    "integrated-1d6-s": "PF2E.TraitDescriptionIntegrated",
    "integrated-1d6-s-versatile-p": "PF2E.TraitDescriptionIntegrated",
    intelligent: "PF2E.TraitDescriptionIntelligent",
    inventor: "PF2E.TraitDescriptionInventor",
    invested: "PF2E.TraitDescriptionInvested",
    investigator: "PF2E.TraitDescriptionInvestigator",
    kami: "PF2E.TraitDescriptionKami",
    kashrishi: "PF2E.TraitDescriptionKashrishi",
    "keep-stone": "PF2E.PreciousMaterialKeepStoneDescription",
    kholo: "PF2E.TraitDescriptionKholo",
    kickback: "PF2E.TraitDescriptionKickback",
    kineticist: "PF2E.TraitDescriptionKineticist",
    kitsune: "PF2E.TraitDescriptionKitsune",
    kobold: "PF2E.TraitDescriptionKobold",
    kovintus: "PF2E.TraitDescriptionKovintus",
    laminar: "PF2E.TraitDescriptionLaminar",
    "launching-dart": "PF2E.TraitDescriptionLaunching",
    leshy: "PF2E.TraitDescriptionLeshy",
    light: "PF2E.TraitDescriptionLight",
    linguistic: "PF2E.TraitDescriptionLinguistic",
    litany: "PF2E.TraitDescriptionLitany",
    lizardfolk: "PF2E.TraitDescriptionLizardfolk",
    lozenge: "PF2E.TraitDescriptionLozenge",
    maftet: "PF2E.TraitDescriptionMaftet",
    magical: "PF2E.TraitDescriptionMagical",
    magus: "PF2E.TraitDescriptionMagus",
    manipulate: "PF2E.TraitDescriptionManipulate",
    mechanical: "PF2E.TraitDescriptionMechanical",
    mental: "PF2E.TraitDescriptionMental",
    merfolk: "PF2E.TraitDescriptionMerfolk",
    metal: "PF2E.TraitDescriptionMetal",
    mindless: "PF2E.TraitDescriptionMindless",
    mindshift: "PF2E.TraitDescriptionMindshift",
    minion: "PF2E.TraitDescriptionMinion",
    minotaur: "PF2E.TraitDescriptionMinotaur",
    misfortune: "PF2E.TraitDescriptionMisfortune",
    missive: "PF2E.TraitDescriptionMissive",
    modification: "PF2E.TraitDescriptionModification",
    modular: "PF2E.TraitDescriptionModular",
    monitor: "PF2E.TraitDescriptionMonitor",
    monk: "PF2E.TraitDescriptionMonk",
    morlock: "PF2E.TraitDescriptionMorlock",
    morph: "PF2E.TraitDescriptionMorph",
    mortic: "PF2E.TraitDescriptionMortic",
    mounted: "PF2E.TraitDescriptionMounted",
    move: "PF2E.TraitDescriptionMove",
    multiclass: "PF2E.TraitDescriptionMulticlass",
    mummy: "PF2E.TraitDescriptionMummy",
    munavri: "PF2E.TraitDescriptionMunavri",
    mutagen: "PF2E.TraitDescriptionMutagen",
    mutant: "PF2E.TraitDescriptionMutant",
    mythic: "PF2E.TraitDescriptionMythic",
    nagaji: "PF2E.TraitDescriptionNagaji",
    nephilim: "PF2E.TraitDescriptionNephilim",
    nindoru: "PF2E.TraitDescriptionNindoru",
    noisy: "PF2E.TraitDescriptionNoisy",
    nonlethal: "PF2E.TraitDescriptionNonlethal",
    nymph: "PF2E.TraitDescriptionNymph",
    oath: "PF2E.TraitDescriptionOath",
    occult: "PF2E.TraitDescriptionOccult",
    oil: "PF2E.TraitDescriptionOil",
    olfactory: "PF2E.TraitDescriptionOlfactory",
    oni: "PF2E.TraitDescriptionOni",
    ooze: "PF2E.TraitDescriptionOoze",
    oracle: "PF2E.TraitDescriptionOracle",
    orc: "PF2E.TraitDescriptionOrc",
    oread: "PF2E.TraitDescriptionOread",
    overflow: "PF2E.TraitDescriptionOverflow",
    paaridar: "PF2E.TraitDescriptionPaaridar",
    palinthanos: "PF2E.TraitDescriptionPalinthanos",
    parry: "PF2E.TraitDescriptionParry",
    peachwood: "PF2E.PreciousMaterialPeachwoodDescription",
    "persona-flirt": "PF2E.TraitPersonaFlirtDescription",
    "persona-guardian": "PF2E.TraitPersonaGuardianDescription",
    "persona-leader": "PF2E.TraitPersonaLeaderDescription",
    "persona-scholar": "PF2E.TraitPersonaScholarDescription",
    "persona-scoundrel": "PF2E.TraitPersonaScoundrelDescription",
    "persona-underdog": "PF2E.TraitPersonaUnderdogDescription",
    "persona-warrior": "PF2E.TraitPersonaWarriorDescription",
    "persona-wildcard": "PF2E.TraitPersonaWildcardDescription",
    phantom: "PF2E.TraitDescriptionPhantom",
    plant: "PF2E.TraitDescriptionPlant",
    poison: "PF2E.TraitDescriptionPoison",
    polymorph: "PF2E.TraitDescriptionPolymorph",
    ponderous: "PF2E.TraitDescriptionPonderous",
    poppet: "PF2E.TraitDescriptionPoppet",
    portable: "PF2E.TraitDescriptionPortable",
    possession: "PF2E.TraitDescriptionPossession",
    potion: "PF2E.TraitDescriptionPotion",
    precious: "PF2E.TraitDescriptionPrecious",
    prediction: "PF2E.TraitDescriptionPrediction",
    processed: "PF2E.TraitDescriptionProcessed",
    press: "PF2E.TraitDescriptionPress",
    primal: "PF2E.TraitDescriptionPrimal",
    propulsive: "PF2E.TraitDescriptionPropulsive",
    protean: "PF2E.TraitDescriptionProtean",
    psyche: "PF2E.TraitDescriptionPsyche",
    psychic: "PF2E.TraitDescriptionPsychic",
    psychopomp: "PF2E.TraitDescriptionPsychopomp",
    qlippoth: "PF2E.TraitDescriptionQlippoth",
    radiation: "PF2E.TraitDescriptionRadiation",
    rage: "PF2E.TraitDescriptionRage",
    akshasa: "PF2E.TraitDescriptionRakshasa",
    ranger: "PF2E.TraitDescriptionRanger",
    "ranged-trip": "PF2E.TraitDescriptionRangedTrip",
    rare: "PF2E.TraitDescriptionRare",
    ratfolk: "PF2E.TraitDescriptionRatfolk",
    razing: "PF2E.TraitDescriptionRazing",
    reach: "PF2E.TraitDescriptionReach",
    "reach-0": "PF2E.TraitDescriptionReach",
    "reach-10": "PF2E.TraitDescriptionReach",
    "reach-100": "PF2E.TraitDescriptionReach",
    "reach-120": "PF2E.TraitDescriptionReach",
    "reach-1000": "PF2E.TraitDescriptionReach",
    "reach-15": "PF2E.TraitDescriptionReach",
    "reach-20": "PF2E.TraitDescriptionReach",
    "reach-200": "PF2E.TraitDescriptionReach",
    "reach-25": "PF2E.TraitDescriptionReach",
    "reach-30": "PF2E.TraitDescriptionReach",
    "reach-40": "PF2E.TraitDescriptionReach",
    "reach-50": "PF2E.TraitDescriptionReach",
    "reach-60": "PF2E.TraitDescriptionReach",
    recovery: "PF2E.TraitDescriptionRecovery",
    reincarnated: "PF2E.TraitDescriptionReincarnated",
    reflection: "PF2E.TraitDescriptionReflection",
    relic: "PF2E.TraitDescriptionRelic",
    reload: "PF2E.TraitDescriptionReload",
    "reload-0": "PF2E.TraitDescriptionReload",
    "reload-1": "PF2E.TraitDescriptionReload",
    "reload-1-min": "PF2E.TraitDescriptionReload",
    "reload-2": "PF2E.TraitDescriptionReload",
    repeating: "PF2E.TraitDescriptionRepeating",
    resonant: "PF2E.TraitDescriptionResonant",
    revelation: "PF2E.TraitDescriptionRevelation",
    rogue: "PF2E.TraitDescriptionRogue",
    saggorak: "PF2E.TraitDescriptionSaggorak",
    sahkil: "PF2E.TraitDescriptionSahkil",
    samsaran: "PF2E.TraitDescriptionSamsaran",
    sanctified: "PF2E.TraitDescriptionSanctified",
    "scatter-10": "PF2E.TraitDescriptionScatter",
    "scatter-15": "PF2E.TraitDescriptionScatter",
    "scatter-20": "PF2E.TraitDescriptionScatter",
    "scatter-5": "PF2E.TraitDescriptionScatter",
    scroll: "PF2E.TraitDescriptionScroll",
    scrying: "PF2E.TraitDescriptionScrying",
    "sea-devil": "PF2E.TraitDescriptionSeaDevil",
    secret: "PF2E.TraitDescriptionSecret",
    sedacthy: "PF2E.TraitDescriptionSedacthy",
    serpentfolk: "PF2E.TraitDescriptionSerpentfolk",
    shabti: "PF2E.TraitDescriptionShabti",
    shadow: "PF2E.TraitDescriptionShadow",
    "shield-throw-20": "PF2E.TraitDescriptionShieldThrow",
    "shield-throw-30": "PF2E.TraitDescriptionShieldThrow",
    shisk: "PF2E.TraitDescriptionShisk",
    shoony: "PF2E.TraitDescriptionShoony",
    shove: "PF2E.TraitDescriptionShove",
    skeleton: "PF2E.TraitDescriptionSkeleton",
    skelm: "PF2E.TraitDescriptionSkelm",
    skill: "PF2E.TraitDescriptionSkill",
    skulk: "PF2E.TraitDescriptionSkulk",
    sleep: "PF2E.TraitDescriptionSleep",
    snare: "PF2E.TraitDescriptionSnare",
    social: "PF2E.TraitDescriptionSocial",
    sonic: "PF2E.TraitDescriptionSonic",
    sorcerer: "PF2E.TraitDescriptionSorcerer",
    soulbound: "PF2E.TraitDescriptionSoulbound",
    spellgun: "PF2E.TraitDescriptionSpellgun",
    spellheart: "PF2E.TraitDescriptionSpellheart",
    spellshape: "PF2E.TraitDescriptionSpellshape",
    spellshot: "PF2E.TraitNoDescription",
    spirit: "PF2E.TraitDescriptionSpirit",
    splash: "PF2E.TraitDescriptionSplash",
    "splash-10": "PF2E.TraitDescriptionSplash10",
    spriggan: "PF2E.TraitDescriptionSpriggan",
    sprite: "PF2E.TraitDescriptionSprite",
    staff: "PF2E.TraitDescriptionStaff",
    stance: "PF2E.TraitDescriptionStance",
    steam: "PF2E.TraitDescriptionSteam",
    stheno: "PF2E.TraitDescriptionStheno",
    strix: "PF2E.TraitDescriptionStrix",
    structure: "PF2E.TraitDescriptionStructure",
    subtle: "PF2E.TraitDescriptionSubtle",
    suli: "PF2E.TraitDescriptionSuli",
    "subjective-gravity": "PF2E.TraitDescriptionSubjectiveGravity",
    summon: "PF2E.TraitDescriptionSummon",
    summoned: "PF2E.TraitDescriptionSummoned",
    summoner: "PF2E.TraitDescriptionSummoner",
    surki: "PF2E.TraitDescriptionSurki",
    swashbuckler: "PF2E.TraitDescriptionSwashbuckler",
    swarm: "PF2E.TraitDescriptionSwarm",
    sweep: "PF2E.TraitDescriptionSweep",
    sylph: "PF2E.TraitDescriptionSylph",
    talisman: "PF2E.TraitDescriptionTalisman",
    talos: "PF2E.TraitDescriptionTalos",
    tandem: "PF2E.TraitDescriptionTandem",
    tane: "PF2E.TraitDescriptionTane",
    tanggal: "PF2E.TraitDescriptionTanggal",
    tattoo: "PF2E.TraitDescriptionTattoo",
    tea: "PF2E.TraitDescriptionTea",
    tearing: "PF2E.TraitDescriptionTearing",
    tech: "PF2E.TraitDescriptionTech",
    telepathy: "PF2E.TraitDescriptionTelepathy",
    teleportation: "PF2E.TraitDescriptionTeleportation",
    tengu: "PF2E.TraitDescriptionTengu",
    tethered: "PF2E.TraitDescriptionTethered",
    thaumaturge: "PF2E.TraitDescriptionThaumaturge",
    thrown: "PF2E.TraitDescriptionThrown",
    "thrown-10": "PF2E.TraitDescriptionThrown",
    "thrown-100": "PF2E.TraitDescriptionThrown",
    "thrown-15": "PF2E.TraitDescriptionThrown",
    "thrown-20": "PF2E.TraitDescriptionThrown",
    "thrown-200": "PF2E.TraitDescriptionThrown",
    "thrown-25": "PF2E.TraitDescriptionThrown",
    "thrown-30": "PF2E.TraitDescriptionThrown",
    "thrown-40": "PF2E.TraitDescriptionThrown",
    "thrown-50": "PF2E.TraitDescriptionThrown",
    "thrown-60": "PF2E.TraitDescriptionThrown",
    "thrown-80": "PF2E.TraitDescriptionThrown",
    tiefling: "PF2E.TraitDescriptionTiefling",
    time: "PF2E.TraitDescriptionTime",
    titan: "PF2E.TraitDescriptionTitan",
    training: "PF2E.TraitDescriptionTraining",
    transcendence: "PF2E.TraitDescriptionTranscendence",
    trap: "PF2E.TraitDescriptionTrap",
    trip: "PF2E.TraitDescriptionTrip",
    troll: "PF2E.TraitDescriptionTroll",
    troop: "PF2E.TraitDescriptionTroop",
    "true-name": "PF2E.TraitDescriptionTrueName",
    twin: "PF2E.TraitDescriptionTwin",
    "two-hand-d10": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d12": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d6": "PF2E.TraitDescriptionTwoHand",
    "two-hand-d8": "PF2E.TraitDescriptionTwoHand",
    unarmed: "PF2E.TraitDescriptionUnarmed",
    uncommon: "PF2E.TraitDescriptionUncommon",
    undine: "PF2E.TraitDescriptionUndine",
    undead: "PF2E.TraitDescriptionUndead",
    unholy: "PF2E.TraitDescriptionUnholy",
    unique: "PF2E.TraitDescriptionUnique",
    unstable: "PF2E.TraitDescriptionUnstable",
    urdefhan: "PF2E.TraitDescriptionUrdefhan",
    vampire: "PF2E.TraitDescriptionVampire",
    vanara: "PF2E.TraitDescriptionVanara",
    vishkanya: "PF2E.TraitDescriptionVishkanya",
    vehicular: "PF2E.TraitDescriptionVehicular",
    velstrac: "PF2E.TraitDescriptionVelstrac",
    venomous: "PF2E.TraitDescriptionVenomous",
    "versatile-acid": "PF2E.TraitDescriptionVersatile",
    "versatile-b": "PF2E.TraitDescriptionVersatile",
    "versatile-cold": "PF2E.TraitDescriptionVersatile",
    "versatile-electricity": "PF2E.TraitDescriptionVersatile",
    "versatile-fire": "PF2E.TraitDescriptionVersatile",
    "versatile-force": "PF2E.TraitDescriptionVersatile",
    "versatile-p": "PF2E.TraitDescriptionVersatile",
    "versatile-poison": "PF2E.TraitDescriptionVersatile",
    "versatile-s": "PF2E.TraitDescriptionVersatile",
    "versatile-sonic": "PF2E.TraitDescriptionVersatile",
    "versatile-spirit": "PF2E.TraitDescriptionVersatile",
    "versatile-vitality": "PF2E.TraitDescriptionVersatile",
    "versatile-void": "PF2E.TraitDescriptionVersatile",
    vigilante: "PF2E.TraitDescriptionVigilante",
    virulent: "PF2E.TraitDescriptionVirulent",
    visual: "PF2E.TraitDescriptionVisual",
    vitality: "PF2E.TraitDescriptionVitality",
    void: "PF2E.TraitDescriptionVoid",
    "volley-20": "PF2E.TraitDescriptionVolley",
    "volley-30": "PF2E.TraitDescriptionVolley",
    "volley-50": "PF2E.TraitDescriptionVolley",
    "volley-60": "PF2E.TraitDescriptionVolley",
    wand: "PF2E.TraitDescriptionWand",
    wandering: "PF2E.TraitDescriptionWandering",
    water: "PF2E.TraitDescriptionWater",
    wayang: "PF2E.TraitDescriptionWayang",
    werecreature: "PF2E.TraitDescriptionWerecreature",
    wight: "PF2E.TraitDescriptionWight",
    witch: "PF2E.TraitDescriptionWitch",
    wizard: "PF2E.TraitDescriptionWizard",
    wraith: "PF2E.TraitDescriptionWraith",
    wood: "PF2E.TraitDescriptionWood",
    wyrwood: "PF2E.TraitDescriptionWyrwood",
    xulgath: "PF2E.TraitDescriptionXulgath",
    zombie: "PF2E.TraitDescriptionZombie",
    ...preciousMaterialDescriptions,
};

export {
    actionTraits,
    ancestryTraits,
    armorTraits,
    backgroundTraits,
    classTraits,
    consumableTraits,
    creatureTraits,
    damageTraits,
    effectTraits,
    elementTraits,
    energyDamageTypes,
    equipmentTraits,
    featTraits,
    hazardTraits,
    kingmakerTraits,
    magicTraditions,
    npcAttackTraits,
    otherArmorTags,
    otherConsumableTags,
    otherWeaponTags,
    preciousMaterials,
    shieldTraits,
    spellTraits,
    traitDescriptions,
    vehicleTraits,
    weaponTraits,
    type ElementTrait,
};
