import { AlignmentTrait } from "@actor/creature/data";

// Ancestry and heritage traits
const ancestryTraits = {
    aasimar: "PF2E.TraitAasimar",
    aberration: "PF2E.TraitAberration",
    anadi: "PF2E.TraitAnadi",
    android: "PF2E.TraitAndroid",
    aphorite: "PF2E.TraitAphorite",
    automaton: "PF2E.TraitAutomaton",
    azarketi: "PF2E.TraitAzarketi",
    beastkin: "PF2E.TraitBeastkin",
    catfolk: "PF2E.TraitCatfolk",
    changeling: "PF2E.TraitChangeling",
    conrasu: "PF2E.TraitConrasu",
    dhampir: "PF2E.TraitDhampir",
    duskwalker: "PF2E.TraitDuskwalker",
    dwarf: "PF2E.TraitDwarf",
    elf: "PF2E.TraitElf",
    fetchling: "PF2E.TraitFetchling",
    fleshwarp: "PF2E.TraitFleshwarp",
    ganzi: "PF2E.TraitGanzi",
    geniekin: "PF2E.TraitGeniekin",
    gnoll: "PF2E.TraitGnoll",
    gnome: "PF2E.TraitGnome",
    goblin: "PF2E.TraitGoblin",
    goloma: "PF2E.TraitGoloma",
    grippli: "PF2E.TraitGrippli",
    "half-elf": "PF2E.TraitHalfElf",
    halfling: "PF2E.TraitHalfling",
    "half-orc": "PF2E.TraitHalfOrc",
    human: "PF2E.TraitHuman",
    hobgoblin: "PF2E.TraitHobgoblin",
    kitsune: "PF2E.TraitKitsune",
    kobold: "PF2E.TraitKobold",
    ifrit: "PF2E.TraitIfrit",
    leshy: "PF2E.TraitLeshy",
    lizardfolk: "PF2E.TraitLizardfolk",
    orc: "PF2E.TraitOrc",
    oread: "PF2E.TraitOread",
    poppet: "PF2E.TraitPoppet",
    ratfolk: "PF2E.TraitRatfolk",
    shisk: "PF2E.TraitShisk",
    shoony: "PF2E.TraitShoony",
    sprite: "PF2E.TraitSprite",
    strix: "PF2E.TraitStrix",
    suli: "PF2E.TraitSuli",
    sylph: "PF2E.TraitSylph",
    tengu: "PF2E.TraitTengu",
    tiefling: "PF2E.TraitTiefling",
    undine: "PF2E.TraitUndine",
};

// Secondary traits of ancestries and heritages
const ancestryItemTraits = {
    ...ancestryTraits,
    amphibious: "PF2E.TraitAmphibious",
    fey: "PF2E.TraitFey",
    fungus: "PF2E.TraitFungus",
    humanoid: "PF2E.TraitHumanoid",
    plant: "PF2E.TraitPlant",
};

const elementalTraits = {
    air: "PF2E.TraitAir",
    earth: "PF2E.TraitEarth",
    fire: "PF2E.TraitFire",
    water: "PF2E.TraitWater",
};

const energyDamageTypes = {
    acid: "PF2E.TraitAcid",
    cold: "PF2E.TraitCold",
    electricity: "PF2E.TraitElectricity",
    fire: "PF2E.TraitFire",
    force: "PF2E.TraitForce",
    negative: "PF2E.TraitNegative",
    positive: "PF2E.TraitPositive",
    sonic: "PF2E.TraitSonic",
};

const creatureTraits = {
    ...ancestryItemTraits,
    ...elementalTraits,
    ...energyDamageTypes,
    aberration: "PF2E.TraitAberration",
    aeon: "PF2E.TraitAeon",
    aesir: "PF2E.TraitAesir",
    agathion: "PF2E.TraitAgathion",
    alchemical: "PF2E.TraitAlchemical",
    anugobu: "PF2E.TraitAnugobu",
    angel: "PF2E.TraitAngel",
    animal: "PF2E.TraitAnimal",
    aquatic: "PF2E.TraitAquatic",
    arcane: "PF2E.TraitArcane",
    archon: "PF2E.TraitArchon",
    astral: "PF2E.TraitAstral",
    asura: "PF2E.TraitAsura",
    azata: "PF2E.TraitAzata",
    beast: "PF2E.TraitBeast",
    boggard: "PF2E.TraitBoggard",
    caligni: "PF2E.TraitCaligni",
    celestial: "PF2E.TraitCelestial",
    "charau-ka": "PF2E.TraitCharauKa",
    clockwork: "PF2E.TraitClockwork",
    couatl: "PF2E.TraitCouatl",
    construct: "PF2E.TraitConstruct",
    daemon: "PF2E.TraitDaemon",
    demon: "PF2E.TraitDemon",
    dero: "PF2E.TraitDero",
    devil: "PF2E.TraitDevil",
    div: "PF2E.TraitDiv",
    divine: "PF2E.TraitDivine",
    dinosaur: "PF2E.TraitDinosaur",
    dragon: "PF2E.TraitDragon",
    dream: "PF2E.TraitDream",
    drow: "PF2E.TraitDrow",
    duergar: "PF2E.TraitDuergar",
    duskwalker: "PF2E.TraitDuskwalker",
    eidolon: "PF2E.TraitEidolon",
    elemental: "PF2E.TraitElemental",
    ethereal: "PF2E.TraitEthereal",
    evocation: "PF2E.TraitEvocation",
    fiend: "PF2E.TraitFiend",
    formian: "PF2E.TraitFormian",
    fungus: "PF2E.TraitFungus",
    genie: "PF2E.TraitGenie",
    ghoran: "PF2E.TraitGhoran",
    ghost: "PF2E.TraitGhost",
    ghoul: "PF2E.TraitGhoul",
    giant: "PF2E.TraitGiant",
    golem: "PF2E.TraitGolem",
    gremlin: "PF2E.TraitGremlin",
    grioth: "PF2E.TraitGrioth",
    grippli: "PF2E.TraitGrippli",
    hag: "PF2E.TraitHag",
    hantu: "PF2E.TraitHantu",
    herald: "PF2E.TraitHerald",
    humanoid: "PF2E.TraitHumanoid",
    ifrit: "PF2E.TraitIfrit",
    ikeshti: "PF2E.TraitIkeshti",
    illusion: "PF2E.TraitIllusion",
    incorporeal: "PF2E.TraitIncorporeal",
    inevitable: "PF2E.TraitInevitable",
    kami: "PF2E.TraitKami",
    kovintus: "PF2E.TraitKovintus",
    light: "PF2E.TraitLight",
    locathah: "PF2E.TraitLocathah",
    mental: "PF2E.TraitMental",
    merfolk: "PF2E.TraitMerfolk",
    mindless: "PF2E.TraitMindless",
    minion: "PF2E.TraitMinion",
    monitor: "PF2E.TraitMonitor",
    mortic: "PF2E.TraitMortic",
    mummy: "PF2E.TraitMummy",
    munavri: "PF2E.TraitMunavri",
    mutant: "PF2E.TraitMutant",
    nagaji: "PF2E.TraitNagaji",
    nymph: "PF2E.TraitNymph",
    oni: "PF2E.TraitOni",
    ooze: "PF2E.TraitOoze",
    orc: "PF2E.TraitOrc",
    oread: "PF2E.TraitOread",
    paaridar: "PF2E.TraitPaaridar",
    petitioner: "PF2E.TraitPetitioner",
    phantom: "PF2E.TraitPhantom",
    protean: "PF2E.TraitProtean",
    psychopomp: "PF2E.TraitPsychopomp",
    qlippoth: "PF2E.TraitQlippoth",
    rakshasa: "PF2E.TraitRakshasa",
    sahkil: "PF2E.TraitSahkil",
    samsaran: "PF2E.TraitSamsaran",
    "sea devil": "PF2E.TraitSeaDevil",
    seugathi: "PF2E.TraitSeugathi",
    serpentfolk: "PF2E.TraitSerpentfolk",
    shabti: "PF2E.TraitShabti",
    shadow: "PF2E.TraitShadow",
    shobhad: "PF2E.TraitShobhad",
    siktempora: "PF2E.TraitSiktempora",
    skeleton: "PF2E.TraitSkeleton",
    skelm: "PF2E.TraitSkelm",
    skulk: "PF2E.TraitSkulk",
    soulbound: "PF2E.TraitSoulbound",
    spirit: "PF2E.TraitSpirit",
    spriggan: "PF2E.TraitSpriggan",
    stheno: "PF2E.TraitStheno",
    swarm: "PF2E.TraitSwarm",
    sylph: "PF2E.TraitSylph",
    tane: "PF2E.TraitTane",
    tanggal: "PF2E.TraitTanggal",
    tengu: "PF2E.TraitTengu",
    time: "PF2E.TraitTime",
    titan: "PF2E.TraitTitan",
    troll: "PF2E.TraitTroll",
    troop: "PF2E.TraitTroop",
    undead: "PF2E.TraitUndead",
    undine: "PF2E.TraitUndine",
    urdefhan: "PF2E.TraitUrdefhan",
    vampire: "PF2E.TraitVampire",
    vanara: "PF2E.TraitVanara",
    velstrac: "PF2E.TraitVelstrac",
    vishkanya: "PF2E.TraitVishkanya",
    wayang: "PF2E.TraitWayang",
    werecreature: "PF2E.TraitWerecreature",
    wight: "PF2E.TraitWight",
    wraith: "PF2E.TraitWraith",
    wyrwood: "PF2E.TraitWyrwood",
    xulgath: "PF2E.TraitXulgath",
    zombie: "PF2E.TraitZombie",
};

const alignmentTraits: Record<AlignmentTrait, string> = {
    chaotic: "PF2E.TraitChaotic",
    evil: "PF2E.TraitEvil",
    good: "PF2E.TraitGood",
    lawful: "PF2E.TraitLawful",
};

const vehicleTraits = {
    magical: "PF2E.TraitMagical",
};

export {
    alignmentTraits,
    ancestryItemTraits,
    ancestryTraits,
    creatureTraits,
    elementalTraits,
    energyDamageTypes,
    vehicleTraits,
};
