import { WorldDocumentType } from "@common/constants.mjs";

export { ActiveEffectSource, default as BaseActiveEffect } from "./active-effect.mjs";
export { default as BaseActorDelta } from "./actor-delta.mjs";
export { ActorSource, default as BaseActor } from "./actor.mjs";
export { AdventureSource, default as BaseAdventure } from "./adventure.mjs";
export { default as BaseAmbientLight } from "./ambient-light.mjs";
export { AmbientSoundSource, default as BaseAmbientSound } from "./ambient-sound.mjs";
export { default as BaseCard, CardFaceData } from "./card.mjs";
export { default as BaseCards } from "./cards.mjs";
export { default as BaseChatMessage, ChatMessageFlags, ChatMessageSource, ChatSpeakerData } from "./chat-message.mjs";
export { default as BaseCombat, CombatSource } from "./combat.mjs";
export { default as BaseCombatantGroup } from "./combatant-group.mjs";
export { default as BaseCombatant, CombatantSource } from "./combatant.mjs";
export { default as BaseDrawing, DrawingSource } from "./drawing.mjs";
export { default as BaseFogExploration, FogExplorationSource } from "./fog-exploration.mjs";
export { default as BaseFolder, FolderSource } from "./folder.mjs";
export { default as BaseItem, ItemSchema, ItemSource } from "./item.mjs";
export { default as BaseJournalEntryPage } from "./journal-entry-page.mjs";
export { default as BaseJournalEntry, JournalEntrySource } from "./journal-entry.mjs";
export { default as BaseMacro, MacroSource } from "./macro.mjs";
export { default as BaseMeasuredTemplate, MeasuredTemplateSource } from "./measured-template.mjs";
export { default as BaseNote, NoteSource } from "./note.mjs";
export { default as BasePlaylistSound, PlaylistSoundSource } from "./playlist-sound.mjs";
export { default as BasePlaylist } from "./playlist.mjs";
export { default as BaseRegionBehavior } from "./region-behavior.mjs";
export { default as BaseRegion, RegionSource } from "./region.mjs";
export { default as BaseRollTable, RollTableSource } from "./roll-table.mjs";
export { default as BaseScene, SceneSource } from "./scene.mjs";
export { default as BaseSetting } from "./setting.mjs";
export { default as BaseTableResult, TableResultSource } from "./table-result.mjs";
export { default as BaseTile, TileSource } from "./tile.mjs";
export { default as BaseToken, TokenSource } from "./token.mjs";
export { default as BaseUser, UserSource } from "./user.mjs";
export { default as BaseWall, WallSource } from "./wall.mjs";

export type ActorUUID = `Actor.${string}` | `${TokenDocumentUUID}.Actor.${string}` | CompendiumActorUUID;
export type CompendiumActorUUID = `Compendium.${string}.Actor.${string}`;
export type CompendiumItemUUID = `Compendium.${string}.Item.${string}`;
export type EmbeddedItemUUID = `${ActorUUID}.Item.${string}`;
export type ItemUUID = WorldItemUUID | EmbeddedItemUUID | CompendiumItemUUID;
export type TokenDocumentUUID = `Scene.${string}.Token.${string}`;
export type UserUUID = `User.${string}`;
export type WorldDocumentUUID = `${WorldDocumentType}.${string}`;
export type WorldItemUUID = `Item.${string}`;
